### ISSUE TITLE
Attached DI based nodeset file configuration in the nodeserver leads to exception when browsed from UAExpert client. The same nodeset works fine in version 2.41.0

### ISSUE THREAD

**Issue by Graos** [node-opcua/node-opcua#1031]
**Current behavior**
Attached DI based nodeset file configuration in the nodeserver leads to exception when browsed from UAExpert client.

1.Load the attached nodeset file to the node server and start the server
2. Try to connect to the server from UA expert client
3. Node server gets into exception.

**Screenshots**

\node_modules\node-opcua-server\dist\opcua_server.js:1641
                    throw new Error("internal error");
                    ^

Error: internal error
    at ServerEngine.<anonymous> (\node_modules\node-opcua-server\dist\opcua_server.js:1641:27)
    at cb (util.js:207:31)
    at util.js:191:10
    at hidden (internal/errors.js:294:14)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

- ( ) my request is related to node-opcua acting as an OPCUA SERVER

- ( ) I have installed node-opcua as a package ( using npm install )

- Device: ______
- OS version: ______

    - ( ) Windows : version : ______
    - ( ) Linux : version : ______
    - ( ) MacOs : version : ______
    - ( ) Raspbian: version : ______
    - ( ) Other : specify : ______

- Description of the other OPCUA system I am trying to connect to:

    - Name: ______
    - Version: ______
    - Manufacturer/Software vendor: ______
    - link to the manufacturer or product site: https://

- **node-opcua version:** : 2.47.0
[LT100LevelTransmitter.zip](https://github.com/node-opcua/node-opcua/files/6886285/LT100LevelTransmitter.zip)

  
  

- **Node:**
  `node --version` =

**Comment by Graos** [comment]
Adding just a DI nodeset2.xml file itself results in exception when any client browse the Node OPCUA server address space.
