### ISSUE TITLE
Error: getExtensionObjectConstructorFromBinaryEncoding cannot find constructor for binaryEncoding

### ISSUE THREAD

**Issue by priyanka01deb** [node-opcua/node-opcua#1033]
Hello,
I'm trying to read a Extension Object Type variable with Siemens S7-1500 PLC.
I have gone through the below forum and tried to implement all possible way to read opaque structures. 
https://github.com/node-opcua/node-opcua/issues/320

![image](https://user-images.githubusercontent.com/36146244/127335820-c92243c9-3d88-4512-9990-71ee4e5dafa3.png)

But every time, I'm getting below error.
Error: getExtensionObjectConstructorFromBinaryEncoding cannot find constructor for binaryEncoding ns=4;i=5003

Yet, I am able to see the structure type in log 
![image](https://user-images.githubusercontent.com/36146244/127336594-9dd3f282-20c2-46f8-8e25-a671d453a40e.png)

Currently, The PLC Server is using OPC UA version 1.04
My Address Model looks like below :
![image](https://user-images.githubusercontent.com/36146244/127981366-fda44b73-4ea6-4ef2-81d6-db36dea8acbb.png)

![image](https://user-images.githubusercontent.com/36146244/127981064-945e7ede-90f3-4a55-9843-f48aeb8fd9db.png)

Interestingly I found the below disclaimer regarding 'DataTypeDefinition' attribute and latest OPC UA version(1.04) compatibility inside the library
![image](https://user-images.githubusercontent.com/36146244/127981768-e11aa3e9-119b-48e3-a54c-0732b65e7d49.png)

and figured out the library doesn't support the latest OPC UA version for Structure types. It's reading the user defined structures from the 'SimanticStructures' folder which is deprecated from OPC version 1.04.
In version 1.04, user defined structures are listed inside the Structure folder instead (refer the above address model)

Any possibility to support OPC UA 1.0.4 version ?

Thanks in advance

**Comment by erossignon** [comment]
a fix will be available soon, ( stay tuned on #1037)

**Comment by erossignon** [comment]
fixed in [node-opcua@2.49.0](https://github.com/node-opcua/node-opcua/releases/tag/v2.49.0)

**Comment by priyanka01deb** [comment]
Thank you so much for your support!

**Comment by mg90707** [comment]
When I disable the "Legacy data type definitions according to OPC UA specification <= V1.03" on my Siemens 1511 PLC I get the following error when attempting to read a custom structure:
`....populate_data_type_manager_104:49    Error Error:  Cannot find dataType Definition ! with nodeId =ns=3;i=3400`
and it seems as if node-opc-ua (v2.51.0) attempts to read the old XML type defintion which is not present anymore.
When activating the 1.03 "TypeDictionary" again it works without problems. However with UA Expert I can browse the type definitions (V1.04). Do I have to set some flag or anything before node-opc-ua works with the new type defition format?

Thanks for your help!

**Comment by david114** [comment]
@mg90707
Have you found a feasible solution to this problem?
I'm currently facing the same issue, receiving similar error messages, although setting 
`Legacy data type definitions according to OPC UA specification <= V1.03
`
to true.

```
| 11:54:58.249Z :populate_data_type_manager_104:38    Error Error:  Cannot find dataType Definition ! with nodeId =ns=2;i=6522
|  ...                                                    at /usr/src/app/node_modules/node-opcua-client-dynamic-extension-object/dist/private/populate_data_type_manager_104.js:31:23
|  ...                                                    at Generator.next (<anonymous>)
|  ...                                                    at fulfilled (/usr/src/app/node_modules/node-opcua-client-dynamic-extension-object/dist/private/populate_data_type_manager_104.js:5:58)  
|  ...                                                    at processTicksAndRejections (node:internal/process/task_queues:96:5)
| 11:54:58.250Z :populate_data_type_manager_104:167   err= Error
|  ...                                                    at assert (/usr/src/app/node_modules/node-opcua-assert/dist/index.js:11:21)
|  ...                                                    at /usr/src/app/node_modules/node-opcua-client-dynamic-extension-object/dist/private/populate_data_type_manager_104.js:164:52
|  ...                                                    at Generator.next (<anonymous>)
|  ...                                                    at fulfilled (/usr/src/app/node_modules/node-opcua-client-dynamic-extension-object/dist/private/populate_data_type_manager_104.js:5:58)  
|  ...                                                    at processTicksAndRejections (node:internal/process/task_queues:96:5)
| 11:54:58.311Z :populate_data_type_manager_104:38    Error Error:  Cannot find dataType Definition ! with nodeId =ns=2;i=6525
|  ...                                                    at /usr/src/app/node_modules/node-opcua-client-dynamic-extension-object/dist/private/populate_data_type_manager_104.js:31:23
|  ...                                                    at Generator.next (<anonymous>)
|  ...                                                    at fulfilled (/usr/src/app/node_modules/node-opcua-client-dynamic-extension-object/dist/private/populate_data_type_manager_104.js:5:58)  
|  ...                                                    at processTicksAndRejections (node:internal/process/task_queues:96:5)
| 11:54:58.312Z :populate_data_type_manager_104:167   err= Error
|  ...                                                    at assert (/usr/src/app/node_modules/node-opcua-assert/dist/index.js:11:21)
|  ...                                                    at /usr/src/app/node_modules/node-opcua-client-dynamic-extension-object/dist/private/populate_data_type_manager_104.js:164:52
|  ...                                                    at Generator.next (<anonymous>)
|  ...                                                    at fulfilled (/usr/src/app/node_modules/node-opcua-client-dynamic-extension-object/dist/private/populate_data_type_manager_104.js:5:58)  
|  ...                                                    at processTicksAndRejections (node:internal/process/task_queues:96:5)
| 11:54:58.359Z :populate_data_type_manager_104:38    Error Error:  Cannot find dataType Definition ! with nodeId =ns=3;i=3400
|  ...                                                    at /usr/src/app/node_modules/node-opcua-client-dynamic-extension-object/dist/private/populate_data_type_manager_104.js:31:23
|  ...                                                    at Generator.next (<anonymous>)
|  ...                                                    at fulfilled (/usr/src/app/node_modules/node-opcua-client-dynamic-extension-object/dist/private/populate_data_type_manager_104.js:5:58)  
|  ...                                                    at processTicksAndRejections (node:internal/process/task_queues:96:5)
| 11:54:58.359Z :populate_data_type_manager_104:167   err= Error
|  ...                                                    at assert (/usr/src/app/node_modules/node-opcua-assert/dist/index.js:11:21)
|  ...                                                    at /usr/src/app/node_modules/node-opcua-client-dynamic-extension-object/dist/private/populate_data_type_manager_104.js:164:52
|  ...                                                    at Generator.next (<anonymous>)
|  ...                                                    at fulfilled (/usr/src/app/node_modules/node-opcua-client-dynamic-extension-object/dist/private/populate_data_type_manager_104.js:5:58)  
|  ...                                                    at processTicksAndRejections (node:internal/process/task_queues:96:5)
| 11:54:58.745Z :populate_data_type_manager_104:38    Error Error:  Cannot find dataType Definition ! with nodeId =ns=2;i=15888
|  ...                                                    at /usr/src/app/node_modules/node-opcua-client-dynamic-extension-object/dist/private/populate_data_type_manager_104.js:31:23
|  ...                                                    at Generator.next (<anonymous>)
|  ...                                                    at fulfilled (/usr/src/app/node_modules/node-opcua-client-dynamic-extension-object/dist/private/populate_data_type_manager_104.js:5:58)  
|  ...                                                    at processTicksAndRejections (node:internal/process/task_queues:96:5)
| 11:54:58.746Z :populate_data_type_manager_104:167   err= Error
|  ...                                                    at assert (/usr/src/app/node_modules/node-opcua-assert/dist/index.js:11:21)
|  ...                                                    at /usr/src/app/node_modules/node-opcua-client-dynamic-extension-object/dist/private/populate_data_type_manager_104.js:164:52
|  ...                                                    at Generator.next (<anonymous>)
|  ...                                                    at fulfilled (/usr/src/app/node_modules/node-opcua-client-dynamic-extension-object/dist/private/populate_data_type_manager_104.js:5:58)  
|  ...                                                    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
