### ISSUE TITLE
Error: keepAliveManager already started

### ISSUE THREAD

**Issue by pelis** [node-opcua/node-opcua#1146]
**Current behavior**
this refers to an opca-ua client, it does not lead to a crash - it just leaves a pretty "nasty" console log:
When the client is connected and the opc-ua server shuts down or becomes unreachable, the following message is logged to console <b>AFTER</b> the opc-ua server becomes available again:

```
client_secure_channel_layer   :960   ERROR !!! callback has thrown en error  Error: keepAliveManger already started
 ...                                                    at assert (C:\tlabs\tlabs-nodes\tc-opcua\node_modules\node-opcua-assert\dist\index.js:11:21)
 ...                                                    at ClientSessionImpl.startKeepAliveManager (C:\tlabs\tlabs-nodes\tc-opcua\node_modules\node-opcua-client\dist\private\client_session_impl.js:1020:40)
 ...                                                    at ClientSecureChannelLayer.<anonymous> (C:\tlabs\tlabs-nodes\tc-opcua\node_modules\node-opcua-client\dist\private\opcua_client_impl.js:764:33)
 ...                                                    at modified_callback (C:\tlabs\tlabs-nodes\tc-opcua\node_modules\node-opcua-secure-channel\dist\source\client\client_secure_channel_layer.js:957:31)
 ...                                                    at process_request_callback (C:\tlabs\tlabs-nodes\tc-opcua\node_modules\node-opcua-secure-channel\dist\source\client\client_secure_channel_layer.js:66:5)
 ...                                                    at ClientSecureChannelLayer._on_message_received (C:\tlabs\tlabs-nodes\tc-opcua\node_modules\node-opcua-secure-channel\dist\source\client\client_secure_channel_layer.js:506:9)
 ...                                                    at MessageBuilder.<anonymous> (C:\tlabs\tlabs-nodes\tc-opcua\node_modules\node-opcua-secure-channel\dist\source\client\client_secure_channel_layer.js:132:18)
 ...                                                    at MessageBuilder.emit (events.js:315:20)
 ...                                                    at MessageBuilder._decodeMessageBody (C:\tlabs\tlabs-nodes\tc-opcua\node_modules\node-opcua-secure-channel\dist\source\message_builder.js:210:26)
 ...                                                    at MessageBuilder._feed_messageChunk (C:\tlabs\tlabs-nodes\tc-opcua\node_modules\node-opcua-transport\dist\source\message_builder_base.js:192:18)

```

**Step by step instruction to reproduce**

1. opc-ua client: connect to a server
2. shutdown the server
3. restart the server

**Expected behavior**
I think, a simple warning would be sufficient in this case

    - (x) node-red
    - ( ) other : please specify

- Device: PC
- OS version: windows 10

    - ( ) Windows : version : 10
    - ( ) Linux : version : ubuntu 18.04

- Description of the other OPCUA system I am trying to connect to:

    - Name: open62541
    - Version: ______
    - Manufacturer/Software vendor: ______[
    - link to the manufacturer or product site: ]https://www.open62541.org

- **node-opcua version:** :
  2.64.1

- **Node:**
  `node --version` = 14.16.0

**Comment by erossignon** [comment]
This issue was fixed a while ago in @2.67.0 [5af1c549698ac999d68a6cc8bdf63cbdd01a2475]
