### ISSUE TITLE
Max message size exceeded will crash secure channel

### ISSUE THREAD

**Issue by dark-matter-matters** [node-opcua/node-opcua#1245]
**Current behavior**

Node-opcua-secure-channel will crash when tring to monitor a node with a value exceeding the max length limit. But no message appears and the exception cannot be caught, terminating the client application.

**Describe the bug**

An uncaught exception is raised. 

The line 525 seems to be missing a falsy assertion before accessing *.callback* (it will always crash if the warning on line 517 is displayed) : https://github.com/node-opcua/node-opcua/blob/master/packages/node-opcua-secure-channel/source/client/client_secure_channel_layer.ts#L525

**Step by step instruction to reproduce**

1. Create a session
2. Create a subscription
3. Monitor an item on the Value attribute with a large payload (larger than `TransportSettings.maxMessageSize`)

**Expected behavior**

An error message should be displayed if the value exceeds the max message length. 

**Gist**
 ```typescript
const monitoredItem = await this.subscription.monitor(
  {
    nodeId: nodeId,
    attributeId: AttributeIds.Value,
  },
  {
    queueSize: 2,
    samplingInterval: -1,
    discardOldest: true,
  },
  TimestampsToReturn.Both,
  MonitoringMode.Reporting
);
monitoredItem
  .on("changed", (dataValue: DataValue) => {
    callback(dataValue.value.value.toString());
  })
  .on("err", (message: string) => {
    console.log("[monitoredItem] err", message);
  });

```

```log
[2] 14:27:44.664Z :client_secure_channel_layer   :950   Adjusted timeout =  60000
[2] 14:27:44.664Z :client_base_impl              :312     Client 0 ClientSession emitting  send_request
[2] 14:27:44.664Z :client_base_impl              :312     Client 0 ClientSession emitting  send_chunk
[2] 14:27:44.667Z :client_base_impl              :312     Client 0 ClientSession emitting  receive_chunk
[2] 14:27:44.668Z :message_builder               :137    Sequence Header SequenceHeader { sequenceNumber: 252, requestId: 257 }
[2] 14:27:44.668Z :message_builder               :260   client0 Sequence Number =  252
[2] 14:27:44.670Z :message_builder               :201   client0 message size = 83        body size   = 59        requestHandle =  257 CreateMonitoredItemsResponse
[2] 14:27:44.670Z :client_secure_channel_layer   :957   ------------------------------------- Client receiving response  CreateMonitoredItemsRequest 257 CreateMonitoredItemsResponse err= null securityTokenId= 13
[2] 14:27:44.671Z :client_base_impl              :312     Client 0 ClientSession emitting  receive_response
[2] 14:27:44.676Z :client_base_impl              :312     Client 0 ClientSession emitting  receive_chunk
[2] 14:27:44.677Z :client_secure_channel_layer   :203   request id =  257 Error: max message size exceeded: 65536
[2]  ...                                                    at MessageBuilder._report_error (C:\Projets\PellencST\ecosys-frontend\node_modules\node-opcua-transport\dist\source\message_builder_base.js:128:28)
[2]  ...                                                    at MessageBuilder._append (C:\Projets\PellencST\ecosys-frontend\node_modules\node-opcua-transport\dist\source\message_builder_base.js:156:25)
[2]  ...                                                    at MessageBuilder._feed_messageChunk (C:\Projets\PellencST\ecosys-frontend\node_modules\node-opcua-transport\dist\source\message_builder_base.js:236:25)
[2]  ...                                                    at PacketAssembler.<anonymous> (C:\Projets\PellencST\ecosys-frontend\node_modules\node-opcua-transport\dist\source\message_builder_base.js:64:66)
[2]  ...                                                    at PacketAssembler.emit (node:events:513:28)
[2]  ...                                                    at PacketAssembler.feed (C:\Projets\PellencST\ecosys-frontend\node_modules\node-opcua-packet-assembler\dist\packet_assembler.js:75:18)
[2]  ...                                                    at MessageBuilder.feed (C:\Projets\PellencST\ecosys-frontend\node_modules\node-opcua-transport\dist\source\message_builder_base.js:94:35)
[2]  ...                                                    at ClientSecureChannelLayer._on_receive_message_chunk (C:\Projets\PellencST\ecosys-frontend\node_modules\node-opcua-secure-channel\dist\source\client\client_secure_channel_layer.js:912:29)
[2]  ...                                                    at ClientTCP_transport.<anonymous> (C:\Projets\PellencST\ecosys-frontend\node_modules\node-opcua-secure-channel\dist\source\client\client_secure_channel_layer.js:757:18)[2]  ...                                                    at ClientTCP_transport.emit (node:events:513:28) message was  undefined
[2] 14:27:44.677Z :client_secure_channel_layer   :206   requestData not found for requestId =  257 try with  258
[2] [electronmon] uncaught exception occured
[2] [electronmon] waiting for any change to restart the app
[2] 14:27:44.678Z :client_base_impl              :312     Client 0 ClientSession emitting  receive_chunk
```

**Context**

- (X) my request is related to node-opcua acting as an OPCUA CLIENT
- ( ) my request is related to node-opcua acting as an OPCUA SERVER

- ( ) I have installed node-opcua from source ( using git clone)
- (X) I have installed node-opcua as a package ( using npm install )
- ( ) I am using an application that uses node-opcua

    - ( ) node-red
    - ( ) other : please specify

    - (X) Windows : version : 11 x64

- **node-opcua version:** :
```json
{
"node-opcua": "2.83.0",
"node-opcua-client": "2.83.0"
}
```

- **Node:**

  `node --version` = 16.18.1

**Comment by erossignon** [comment]
Please update to latest node-opcua version
