### ISSUE TITLE
Cannot find encodingDefaultBinary for this object

### ISSUE THREAD

**Issue by ambrogio-galbusera** [node-opcua/node-opcua#1280]
I am trying to create an extensionObject with the following code

```
    const addressSpace = server.engine.addressSpace;
    const ns= addressSpace.getNamespaceIndex("http://opcfoundation.org/UA/PlasticsRubber/GeneralTypes/");
    const activeErrorDataType = addressSpace.findDataType("ActiveErrorDataType",ns);
    const activeError = addressSpace.constructExtensionObject(
        activeErrorDataType,
        {
        id: "Alarm", severity:1, message: "abc"
        });
        console.log(activeError.toString());        
```

Then I create a bind on a node to get the updated value

```
node.bindVariable({
              get: () => {
                        return new opcua.Variant({
                            dataType: opcua.DataType.ExtensionObject,
                            value: activeError,
                            statusCode: opcua.StatusCodes.Good
                        });
                    }
            })
```

But when I try to read the value from a client, I get the following error

```
xxxxxxxxx encoding ExtObj  {"id":"Alarm","severity":1,"message":"abc"}
xxxxxxxxx encoding ExtObj  ActiveError { id: 'Alarm', severity: 1, message: 'abc' }
EXCEPTION CAUGHT WHILE PROCESSING REQUEST !! PublishRequest
{ /*PublishRequest*/
 requestHeader                 /* RequestHeader                    */: {
   authenticationToken         /* NodeId                           */: ns=0;b=bdcd60ecfa73d0e463a14fc2064e95ff
   timeStamp                   /* UtcTime                          */: 2023-06-09T12:49:51.382Z
   requestHandle               /* IntegerId                        */: 1005986               0xf59a2
   returnDiagnostics           /* UInt32                           */: 0               0x0
   auditEntryId                /* UAString                         */: null
   timeoutHint                 /* UInt32                           */: 60000               0xea60
   additionalHeader            /* ExtensionObject                  */: null
 }
 subscriptionAcknowledgements  /* SubscriptionAcknowledgement   [] */: null []
};
 display_trace_from_this_project_only =
Cannot find encodingDefaultBinary for this object

 messages  EXCEPTION CAUGHT WHILE PROCESSING REQUEST !!! PublishRequest
Cannot find encodingDefaultBinary for this object
Error: Cannot find encodingDefaultBinary for this object
    at encodeExtensionObject (/home/admin/package/deploy/node-jmobile-opcua/node_modules/node-opcua-extension-object/src/extension_object.js:66:19)
    at Object.encode (/home/admin/package/deploy/node-jmobile-opcua/node_modules/node-opcua-variant/schemas/Variant_schema.js:265:13)
    at Variant.encode (/home/admin/package/deploy/node-jmobile-opcua/node_modules/node-opcua-variant/_generated_/_auto_generated_Variant.js:117:11)
    at Object.encode (/home/admin/package/deploy/node-jmobile-opcua/node_modules/node-opcua-data-value/schemas/DataValue_schema.js:75:29)
    at DataValue.encode (/home/admin/package/deploy/node-jmobile-opcua/node_modules/node-opcua-data-value/_generated_/_auto_generated_DataValue.js:113:11)
    at MonitoredItemNotification.encode (/home/admin/package/deploy/node-jmobile-opcua/node_modules/node-opcua-service-subscription/_generated_/_auto_generated_MonitoredItemNotification.js:84:15)
    at /home/admin/package/deploy/node-jmobile-opcua/node_modules/node-opcua-service-subscription/_generated_/_auto_generated_DataChangeNotification.js:91:70
    at exports.encodeArray (/home/admin/package/deploy/node-jmobile-opcua/node_modules/node-opcua-basic-types/src/array.js:20:9)
    at DataChangeNotification.encode (/home/admin/package/deploy/node-jmobile-opcua/node_modules/node-opcua-service-subscription/_generated_/_auto_generated_DataChangeNotification.js:91:5)
    at DataChangeNotification.BaseUAObject.binaryStoreSize (/home/admin/package/deploy/node-jmobile-opcua/node_modules/node-opcua-factory/src/factories_baseobject.js:54:10)

```

**Describe the bug**
The constructExtensionObject seems to fail to find the node of the "Default Binary" encoder

**Context**

- ( ) my request is related to node-opcua acting as an OPCUA CLIENT
- (X) my request is related to node-opcua acting as an OPCUA SERVER

- ( ) I have installed node-opcua from source ( using git clone)
- (X) I have installed node-opcua as a package ( using npm install )
- ( ) I am using an application that uses node-opcua

    - ( ) node-red
    - ( ) other : please specify

- Device: Raspberry
- OS version: Linux

    - ( ) Windows : version : ______
    - (X) Linux : version : Bullseye
    - ( ) MacOs : version : ______
    - ( ) Raspbian: version : ______
    - ( ) Other : specify : ______

**Comment by erossignon** [comment]
@ambrogio-galbusera can you provide the entire code ?
In particular, how is the node created ?

See this gist for a working example : https://gist.github.com/erossignon/86b3e45aa1e6b9208aab13b1bdecc6df

**Comment by erossignon** [comment]
@ambrogio-galbusera  ping ?
