### ISSUE TITLE
RangeError [ERR_INVALID_ARG_VALUE]: The argument 'size' is invalid. Received NaN

### ISSUE THREAD

**Issue by faljse** [node-opcua/node-opcua#1282]
Our server fails somewhere inside node-opcua code.

internal opcua error happens here:
```
  const crawler = new NodeCrawler(session);
  const data = await crawler.read("ns=6;i=5002");
```
```
11:04:14.143Z :opcua_server                  :1439  Internal error in issuing response
 ...                                                please contact support@sterfive.com { /*ReadRequest*/
 ...                                                 requestHeader                 /* RequestHeader       */: {
 ...                                                   authenticationToken         /* NodeId              */: ns=0;b=Eh11g6nCBAgcXrBbCnUgRg==
 ...                                                   timestamp                   /* DateTime            */: 2023-06-19T11:04:14.017Z
 ...                                                   requestHandle               /* UInt32              */: 19               0x13
 ...                                                   returnDiagnostics           /* UInt32              */: 0               0x0
 ...                                                   auditEntryId                /* UAString            */:
 ...                                                   timeoutHint                 /* UInt32              */: 60000               0xea60
 ...                                                   additionalHeader            /* ExtensionObject     */: null
 ...                                                 }
 ...                                                 maxAge                        /* Double              */: 0
 ...                                                 timestampsToReturn            /* TimestampsToRetur   */: 2 /*(Both)*/
 ...                                                 nodesToRead                   /* ReadValueId      [] */: [
 ...                                                   { /*0*/
 ...                                                     nodeId                    /* NodeId              */: ns=5;i=258 ...                                                     attributeId               /* UInt32              */: AttributeIds.UserAccessLevel/* 18 */
 ...                                                     indexRange                /* NumericRange        */: NumericRange:<Empty>
 ...                                                     dataEncoding              /* QualifiedName       */: <null>
 ...                                                   },
 ...                                                   { /*1*/
 ...                                                     nodeId                    /* NodeId              */: ns=5;i=259 ...                                                     attributeId               /* UInt32              */: AttributeIds.Description/* 5 */
 ...                                                     indexRange                /* NumericRange        */: NumericRange:<Empty>
 ...                                                     dataEncoding              /* QualifiedName       */: <null>
 ...                                                   },
 ...                                                 .... TRUNCATED ..... (NODEOPCUA_DEBUG_MAXLINE_PER_MESSAGE=25
node:internal/errors:466
    ErrorCaptureStackTrace(err);
    ^

RangeError [ERR_INVALID_ARG_VALUE]: The argument 'size' is invalid. Received NaN
    at allocUnsafe (node:buffer:376:3)
    at new BinaryStream (C:\snapshot\opcuafrontend\node_modules\node-opcua-binary-stream\dist\binaryStream.js:47:87)
    at MessageChunker.chunkSecureMessage (C:\snapshot\opcuafrontend\node_modules\node-opcua-secure-channel\dist\source\message_chunker.js:57:24)
    at ServerSecureChannelLayer.send_response (C:\snapshot\opcuafrontend\node_modules\node-opcua-secure-channel\dist\source\server\server_secure_channel_layer.js:414:29)
    at sendResponse (C:\snapshot\opcuafrontend\node_modules\node-opcua-server\dist\opcua_server.js:1433:36)
    at C:\snapshot\opcuafrontend\node_modules\node-opcua-server\dist\opcua_server.js:1746:17
    at C:\snapshot\opcuafrontend\node_modules\node-opcua-server\dist\server_engine.js:1489:13
    at C:\snapshot\opcuafrontend\node_modules\async\dist\async.js:251:13
    at wrapper (C:\snapshot\opcuafrontend\node_modules\async\dist\async.js:271:20)
    at iteratorCallback (C:\snapshot\opcuafrontend\node_modules\async\dist\async.js:501:17) {
  code: 'ERR_INVALID_ARG_VALUE'
}

```
- **node-opcua version:** : 2.99.0

**Comment by erossignon** [comment]
node-opcua-client-crawler is now deprecated not maitained anymore and has been deprecated since v2.82.0 ( see https://github.com/node-opcua/node-opcua/releases/tag/v2.82.0 )

It has been replaced by @sterfive/crawler that is available with Sterfive enterprise edition of node-opcua.  contact us at https://www.sterfive.com/contact.

@sterfive/crawler is a complete rewrite and uses a brand new approach for efficiently crawling the address space, it fixes many issues found in the old implementation.
