### ISSUE TITLE
node-opcua Client does not retry connection ,when server is not available , when security Policy other NONE is used

### ISSUE THREAD

**Issue by GaneshRaos** [node-opcua/node-opcua#1357]
node-opcua Client: 2.123.0
nodejs version: 2.19.0

node-opcua Client does not retry connection ,when server is not available , when security Policy other NONE is used. see below the error thrown. However when NONE security policy "Backoff" events is repeatedly called with a time delay provided.

16:23:33.351Z :client_base_impl              :92    Fail to connect to server at opc.tcp://localhost:26543 to collect server's certificate (in findEndpoint)
 ...                                                 (err =The connection cannot be established with server opc.tcp://localhost:26543 .
 ...                                                Please check that the server is up and running or your network configuration.
 ...                                                Err = (connect ECONNREFUSED 192.168.0.200:26543))
28/03/2024, 17:23:33.354[Error]: --> connection to OPC UA server: opc.tcp://localhost:26543 failed with Error: Fail to connect to server at opc.tcp://localhost:26543 to collect server's certificate (in findEndpoint)
 (err =The connection cannot be established with server opc.tcp://localhost:26543 .
Please check that the server is up and running or your network configuration.
Err = (connect ECONNREFUSED 192.168.0.200:26543))
\node_modules\node-opcua-client\dist\private\client_base_impl.js:692
                    err = new Error("The connection cannot be established with server " +
                          ^

Error: Fail to connect to server at opc.tcp://localhost:26543 to collect server's certificate (in findEndpoint)
 (err =The connection cannot be established with server opc.tcp://localhost:26543 .
Please check that the server is up and running or your network configuration.
Err = (connect ECONNREFUSED 192.168.0.200:26543))
    at \node_modules\node-opcua-client\dist\private\client_base_impl.js:692:27
    at \node_modules\node-opcua-client\dist\private\client_base_impl.js:506:25
    at \node_modules\node-opcua-secure-channel\dist\source\client\client_secure_channel_layer.js:395:13
    at \node_modules\async\dist\async.js:3683:19
    at wrapper (\node_modules\async\dist\async.js:273:20)
    at replenish (\node_modules\async\dist\async.js:443:29)
    at \node_modules\async\dist\async.js:453:13
    at eachOfLimit (\node_modules\async\dist\async.js:479:36)
    at awaitable (\node_modules\async\dist\async.js:212:32)
    at eachOfSeries (\node_modules\async\dist\async.js:815:16)

Node.js v18.19.0
Press any key to continue...

**Comment by GaneshRaos** [comment]
closing as this is an issue with the local implementation.
