### ISSUE TITLE
"Cannot find StructureType constructor" when decoding extension object 

### ISSUE THREAD

**Issue by champloo** [node-opcua/node-opcua#1393]
**Current behavior**

When reading a node I get an error when a nested extension object is being decoded _"resolveDynamicExtensionObjectV err =  Error: Cannot find StructureType constructor for ISA95ParameterDataType - it may be abstract, or it could be a basic type"_

<details>

<summary>See error log output </summary>

```text
22:28:50.547Z :resolve_dynamic_extension_obje:99    Constructor =  MyProductDefinitionDataType
22:28:50.547Z :resolve_dynamic_extension_obje:100   opaqueStructure =  ns=8;i=5017
22:28:50.548Z :resolve_dynamic_extension_obje:101   opaqueStructure =  00000000: 00 00 00 00 0e 00 00 00 45 78 61 6d 70 6c 65 50 72 6f 64 75 63 74 00 00 00 00 00 00 20 40 00 00 00 00 00 00 59 40 04 00 00 00 01 00 00 00 14 00 00 00 43 75 73 74 6f 6d 65 72 20 4c 6f 67 6f 20 6f 6e 20 45 4f 54 01 00 00 00 03 02 00 00 00 65 6e 0f 00 00 00 48 53 41 4c 6f 67 6f 5f 38 6d 6d 2e 65 7a 33                                                                                                    ........ExampleProduct...... @......Y@............Customer Logo on EOT.........en....HSALogo_8mm.ez3
 ...                                                
 ...                                                 .... ( 1555)
22:28:50.548Z :resolve_dynamic_extension_obje:102   00000000: 00 00 00 00 0e 00 00 00 45 78 61 6d 70 6c 65 50 72 6f 64 75 63 74 00 00 00 00 00 00 20 40 00 00    ........ExampleProduct...... @..
 ...                                                00000020: 00 00 00 00 59 40 04 00 00 00 01 00 00 00 14 00 00 00 43 75 73 74 6f 6d 65 72 20 4c 6f 67 6f 20    ....Y@............Customer Logo 
 ...                                                00000040: 6f 6e 20 45 4f 54 01 00 00 00 03 02 00 00 00 65 6e 0f 00 00 00 48 53 41 4c 6f 67 6f 5f 38 6d 6d    on EOT.........en....HSALogo_8mm
 ...                                                00000060: 2e 65 7a 33 04 00 00 00 03 00 00 00 05 00 00 00 50 6f 77 65 72 0b 00 00 00 00 00 00 2e 40 01 00    .ez3............Power........@..
 ...                                                00000080: 00 00 03 02 00 00 00 65 6e 22 00 00 00 4c 61 73 65 72 20 70 6f 77 65 72 20 74 6f 20 62 65 20 75    .......en"...Laser power to be u
 ...                                                000000a0: 73 65 64 20 66 6f 72 20 6d 61 72 6b 69 6e 67 2f 00 00 00 68 74 74 70 3a 2f 2f 77 77 77 2e 6f 70    sed for marking/...http://www.op
 ...                                                000000c0: 63 66 6f 75 6e 64 61 74 69 6f 6e 2e 6f 72 67 2f 55 41 2f 75 6e 69 74 73 2f 75 6e 2f 63 65 66 61    cfoundation.org/UA/units/un/cefa
 ...                                                000000e0: 63 74 54 54 57 00 02 01 00 00 00 57 03 02 00 00 00 65 6e 04 00 00 00 77 61 74 74 03 00 00 00 05    ctTTW......W.....en....watt.....
 ...                                                00000100: 00 00 00 53 70 65 65 64 0b 00 00 00 00 00 40 8f 40 01 00 00 00 03 02 00 00 00 65 6e 18 00 00 00    ...Speed......@.@.........en....
 ...                                                00000120: 4d 61 72 6b 69 6e 67 20 73 70 65 65 64 20 74 6f 20 62 65 20 75 73 65 64 2f 00 00 00 68 74 74 70    Marking speed to be used/...http
 ...                                                00000140: 3a 2f 2f 77 77 77 2e 6f 70 63 66 6f 75 6e 64 61 74 69 6f 6e 2e 6f 72 67 2f 55 41 2f 75 6e 69 74    ://www.opcfoundation.org/UA/unit
 ...                                                00000160: 73 2f 75 6e 2f 63 65 66 61 63 74 36 31 43 00 02 04 00 00 00 6d 6d 2f 73 03 02 00 00 00 65 6e 15    s/un/cefact61C......mm/s.....en.
 ...                                                00000180: 00 00 00 6d 69 6c 6c 69 6d 65 74 72 65 20 70 65 72 20 73 65 63 6f 6e 64 03 00 00 00 09 00 00 00    ...millimetre per second........
 ...                                                000001a0: 4c 6f 6f 70 43 6f 75 6e 74 0b 00 00 00 00 00 00 00 40 01 00 00 00 03 02 00 00 00 65 6e 18 00 00    LoopCount........@.........en...
 ...                                                000001c0: 00 4e 75 6d 62 65 72 20 6f 66 20 6d 61 72 6b 69 6e 67 20 70 61 73 73 65 73 2f 00 00 00 68 74 74    .Number of marking passes/...htt
 ...                                                000001e0: 70 3a 2f 2f 77 77 77 2e 6f 70 63 66 6f 75 6e 64 61 74 69 6f 6e 2e 6f 72 67 2f 55 41 2f 75 6e 69    p://www.opcfoundation.org/UA/uni
 ...                                                00000200: 74 73 2f 75 6e 2f 63 65 66 61 63 74 54 43 41 00 02 00 00 00 00 03 02 00 00 00 65 6e 0e 00 00 00    ts/un/cefactTCA...........en....
 ...                                                00000220: 61 63 74 69 76 69 74 79 20 63 6f 75 6e 74 03 00 00 00 09 00 00 00 46 72 65 71 75 65 6e 63 79 0b    activity count........Frequency.
 ...                                                00000240: 00 00 00 00 00 00 4e 40 01 00 00 00 03 02 00 00 00 65 6e 26 00 00 00 4c 61 73 65 72 20 66 72 65    ......N@.........en&...Laser fre
 ...                                                00000260: 71 75 65 6e 63 79 20 74 6f 20 62 65 20 75 73 65 64 20 66 6f 72 20 6d 61 72 6b 69 6e 67 2f 00 00    quency to be used for marking/..
 ...                                                00000280: 00 68 74 74 70 3a 2f 2f 77 77 77 2e 6f 70 63 66 6f 75 6e 64 61 74 69 6f 6e 2e 6f 72 67 2f 55 41    .http://www.opcfoundation.org/UA
 ...                                                000002a0: 2f 75 6e 69 74 73 2f 75 6e 2f 63 65 66 61 63 74 5a 48 4b 00 02 03 00 00 00 6b 48 7a 03 02 00 00    /units/un/cefactZHK......kHz....
 ...                                                000002c0: 00 65 6e 09 00 00 00 6b 69 6c 6f 68 65 72 74 7a 08 00 00 00 08 00 00 00 44 4d 43 20 43 6f 64 65    .en....kilohertz........DMC Code
 ...                                                000002e0: 00 00 00 00 03 02 00 00 00 65 6e 12 00 00 00 44 49 4e 36 35 33 35 2d 48 41 5f 38 6d 6d 2e 65 7a    .........en....DIN6535-HA_8mm.ez
 ...                                                00000300: 33 01 00 00 00 04 00 00 00 43 6f 64 65 06 00 00 00 54 65 78 74 2e 30 0a 00 00 00 11 00 00 00 44    3........Code....Text.0........D
 ...                                                00000320: 61 74 65 26 74 69 6d 65 20 6f 6e 20 62 61 63 6b 00 00 00 00 03 02 00 00 00 65 6e 0c 00 00 00 54    ate&time on back.........en....T
 ...                                                 .... TRUNCATED ..... (NODEOPCUA_DEBUG_MAXLINE_PER_MESSAGE=25
22:28:50.549Z :resolve_dynamic_extension_obje:103   resolveDynamicExtensionObjectV err =  Error: Cannot find StructureType constructor for ISA95ParameterDataType - it may be abstract, or it could be a basic type
 ...                                                    at DataTypeFactory.getStructureInfoByTypeName (C:\Users\user\source\repos\node-opcua-sample\node_modules\node-opcua-factory\dist\datatype_factory.js:134:15)
 ...                                                    at initializeField (C:\Users\user\source\repos\node-opcua-sample\node_modules\node-opcua-schemas\dist\source\dynamic_extension_object.js:222:53)
 ...                                                    at internal_decodeFields (C:\Users\user\source\repos\node-opcua-sample\node_modules\node-opcua-schemas\dist\source\dynamic_extension_object.js:353:21)
 ...                                                    at decodeFields (C:\Users\user\source\repos\node-opcua-sample\node_modules\node-opcua-schemas\dist\source\dynamic_extension_object.js:378:5)
 ...                                                    at EXTENSION.decode (C:\Users\user\source\repos\node-opcua-sample\node_modules\node-opcua-schemas\dist\source\dynamic_extension_object.js:432:9)
 ...                                                    at EXTENSION.decode (C:\Users\user\source\repos\node-opcua-sample\node_modules\node-opcua-schemas\dist\source\dynamic_extension_object.js:702:19)
 ...                                                    at decodeElement (C:\Users\user\source\repos\node-opcua-sample\node_modules\node-opcua-schemas\dist\source\dynamic_extension_object.js:103:21)
 ...                                                    at decodeArrayOrElement (C:\Users\user\source\repos\node-opcua-sample\node_modules\node-opcua-schemas\dist\source\dynamic_extension_object.js:117:33)
 ...                                                    at internal_decodeFields (C:\Users\user\source\repos\node-opcua-sample\node_modules\node-opcua-schemas\dist\source\dynamic_extension_object.js:359:17)
 ...                                                    at decodeFields (C:\Users\user\source\repos\node-opcua-sample\node_modules\node-opcua-schemas\dist\source\dynamic_extension_object.js:378:5)
22:28:50.549Z :resolve_dynamic_extension_obje:110   err Error: BinaryStream.readByteStream error : not enough bytes left in buffer :  bufferLength is 8814 but only 1415 left
 ...                                                    at BinaryStream.readString (C:\Users\user\source\repos\node-opcua-sample\node_modules\node-opcua-binary-stream\dist\binaryStream.js:398:19)
 ...                                                    at decodeString (C:\Users\user\source\repos\node-opcua-sample\node_modules\node-opcua-basic-types\dist\string.js:24:19)
 ...                                                    at decodeElement (C:\Users\user\source\repos\node-opcua-sample\node_modules\node-opcua-schemas\dist\source\dynamic_extension_object.js:89:16)
 ...                                                    at decodeArrayOrElement (C:\Users\user\source\repos\node-opcua-sample\node_modules\node-opcua-schemas\dist\source\dynamic_extension_object.js:124:27)
 ...                                                    at internal_decodeFields (C:\Users\user\source\repos\node-opcua-sample\node_modules\node-opcua-schemas\dist\source\dynamic_extension_object.js:363:17)
 ...                                                    at decodeFields (C:\Users\user\source\repos\node-opcua-sample\node_modules\node-opcua-schemas\dist\source\dynamic_extension_object.js:378:5)
 ...                                                    at EXTENSION.decode (C:\Users\user\source\repos\node-opcua-sample\node_modules\node-opcua-schemas\dist\source\dynamic_extension_object.js:432:9)
 ...                                                    at EXTENSION.decode (C:\Users\user\source\repos\node-opcua-sample\node_modules\node-opcua-schemas\dist\source\dynamic_extension_object.js:702:19)
 ...                                                    at decodeElement (C:\Users\user\source\repos\node-opcua-sample\node_modules\node-opcua-schemas\dist\source\dynamic_extension_object.js:103:21)
 ...                                                    at decodeArrayOrElement (C:\Users\user\source\repos\node-opcua-sample\node_modules\node-opcua-schemas\dist\source\dynamic_extension_object.js:117:33)
22:28:50.550Z :resolve_dynamic_extension_obje:111   opaqueStructure =  ns=8;i=5017
22:28:50.550Z :resolve_dynamic_extension_obje:112   opaqueStructure =  0x00000000: 00 00 00 00 0e 00 00 00 45 78 61 6d 70 6c 65 50 72 6f 64 75 63 74 00 00 00 00 00 00 20 40 00 00 00 00 00 00 59 40 04 00 00 00 01 00 00 00 14 00 00 00 43 75 73 74 6f 6d 65 72 20 4c 6f 67 6f 20 6f 6e 20 45 4f 54 01 00 00 00 03 02 00 00 00 65 6e 0f 00 00 00 48 53 41 4c 6f 67 6f 5f 38 6d 6d 2e 65 7a 33                                                                                                    ........ExampleProduct...... @......Y@............Customer Logo on EOT.........en....HSALogo_8mm.ez3
 ...                                                
 ...                                                 .... ( 1555)
22:28:50.550Z :resolve_dynamic_extension_obje:113   00000000: 00 00 00 00 0e 00 00 00 45 78 61 6d 70 6c 65 50 72 6f 64 75 63 74 00 00 00 00 00 00 20 40 00 00    ........ExampleProduct...... @..
 ...                                                00000020: 00 00 00 00 59 40 04 00 00 00 01 00 00 00 14 00 00 00 43 75 73 74 6f 6d 65 72 20 4c 6f 67 6f 20    ....Y@............Customer Logo 
 ...                                                00000040: 6f 6e 20 45 4f 54 01 00 00 00 03 02 00 00 00 65 6e 0f 00 00 00 48 53 41 4c 6f 67 6f 5f 38 6d 6d    on EOT.........en....HSALogo_8mm
 ...                                                00000060: 2e 65 7a 33 04 00 00 00 03 00 00 00 05 00 00 00 50 6f 77 65 72 0b 00 00 00 00 00 00 2e 40 01 00    .ez3............Power........@..
 ...                                                00000080: 00 00 03 02 00 00 00 65 6e 22 00 00 00 4c 61 73 65 72 20 70 6f 77 65 72 20 74 6f 20 62 65 20 75    .......en"...Laser power to be u
 ...                                                000000a0: 73 65 64 20 66 6f 72 20 6d 61 72 6b 69 6e 67 2f 00 00 00 68 74 74 70 3a 2f 2f 77 77 77 2e 6f 70    sed for marking/...http://www.op
 ...                                                000000c0: 63 66 6f 75 6e 64 61 74 69 6f 6e 2e 6f 72 67 2f 55 41 2f 75 6e 69 74 73 2f 75 6e 2f 63 65 66 61    cfoundation.org/UA/units/un/cefa
 ...                                                000000e0: 63 74 54 54 57 00 02 01 00 00 00 57 03 02 00 00 00 65 6e 04 00 00 00 77 61 74 74 03 00 00 00 05    ctTTW......W.....en....watt.....
 ...                                                00000100: 00 00 00 53 70 65 65 64 0b 00 00 00 00 00 40 8f 40 01 00 00 00 03 02 00 00 00 65 6e 18 00 00 00    ...Speed......@.@.........en....
 ...                                                00000120: 4d 61 72 6b 69 6e 67 20 73 70 65 65 64 20 74 6f 20 62 65 20 75 73 65 64 2f 00 00 00 68 74 74 70    Marking speed to be used/...http
 ...                                                00000140: 3a 2f 2f 77 77 77 2e 6f 70 63 66 6f 75 6e 64 61 74 69 6f 6e 2e 6f 72 67 2f 55 41 2f 75 6e 69 74    ://www.opcfoundation.org/UA/unit
 ...                                                00000160: 73 2f 75 6e 2f 63 65 66 61 63 74 36 31 43 00 02 04 00 00 00 6d 6d 2f 73 03 02 00 00 00 65 6e 15    s/un/cefact61C......mm/s.....en.
 ...                                                00000180: 00 00 00 6d 69 6c 6c 69 6d 65 74 72 65 20 70 65 72 20 73 65 63 6f 6e 64 03 00 00 00 09 00 00 00    ...millimetre per second........
 ...                                                000001a0: 4c 6f 6f 70 43 6f 75 6e 74 0b 00 00 00 00 00 00 00 40 01 00 00 00 03 02 00 00 00 65 6e 18 00 00    LoopCount........@.........en...
 ...                                                000001c0: 00 4e 75 6d 62 65 72 20 6f 66 20 6d 61 72 6b 69 6e 67 20 70 61 73 73 65 73 2f 00 00 00 68 74 74    .Number of marking passes/...htt
 ...                                                000001e0: 70 3a 2f 2f 77 77 77 2e 6f 70 63 66 6f 75 6e 64 61 74 69 6f 6e 2e 6f 72 67 2f 55 41 2f 75 6e 69    p://www.opcfoundation.org/UA/uni
 ...                                                00000200: 74 73 2f 75 6e 2f 63 65 66 61 63 74 54 43 41 00 02 00 00 00 00 03 02 00 00 00 65 6e 0e 00 00 00    ts/un/cefactTCA...........en....
 ...                                                00000220: 61 63 74 69 76 69 74 79 20 63 6f 75 6e 74 03 00 00 00 09 00 00 00 46 72 65 71 75 65 6e 63 79 0b    activity count........Frequency.
 ...                                                00000240: 00 00 00 00 00 00 4e 40 01 00 00 00 03 02 00 00 00 65 6e 26 00 00 00 4c 61 73 65 72 20 66 72 65    ......N@.........en&...Laser fre
 ...                                                00000260: 71 75 65 6e 63 79 20 74 6f 20 62 65 20 75 73 65 64 20 66 6f 72 20 6d 61 72 6b 69 6e 67 2f 00 00    quency to be used for marking/..
 ...                                                00000280: 00 68 74 74 70 3a 2f 2f 77 77 77 2e 6f 70 63 66 6f 75 6e 64 61 74 69 6f 6e 2e 6f 72 67 2f 55 41    .http://www.opcfoundation.org/UA
 ...                                                000002a0: 2f 75 6e 69 74 73 2f 75 6e 2f 63 65 66 61 63 74 5a 48 4b 00 02 03 00 00 00 6b 48 7a 03 02 00 00    /units/un/cefactZHK......kHz....
 ...                                                000002c0: 00 65 6e 09 00 00 00 6b 69 6c 6f 68 65 72 74 7a 08 00 00 00 08 00 00 00 44 4d 43 20 43 6f 64 65    .en....kilohertz........DMC Code
 ...                                                000002e0: 00 00 00 00 03 02 00 00 00 65 6e 12 00 00 00 44 49 4e 36 35 33 35 2d 48 41 5f 38 6d 6d 2e 65 7a    .........en....DIN6535-HA_8mm.ez
 ...                                                00000300: 33 01 00 00 00 04 00 00 00 43 6f 64 65 06 00 00 00 54 65 78 74 2e 30 0a 00 00 00 11 00 00 00 44    3........Code....Text.0........D
 ...                                                00000320: 61 74 65 26 74 69 6d 65 20 6f 6e 20 62 61 63 6b 00 00 00 00 03 02 00 00 00 65 6e 0c 00 00 00 54    ate&time on back.........en....T
 ...                                                 .... TRUNCATED ..... (NODEOPCUA_DEBUG_MAXLINE_PER_MESSAGE=25
```
</details>

The error is reproduced when running the code at https://gist.github.com/champloo/588c448534432cd67c7003aa00e460fb

**Expected behavior**

I expected that the object would be read correctly. The expected object should look something like below. Do note that this error only occurs when the nested object `markingOperations`, which is also an extension object has contents

```
ISA95ParameterDataType {
  ID: 'ProductDefinition',
  value: Variant {
    dataType: 22,
    arrayType: 0,
    value: MyProductDefinitionDataType {
      productID: 'No Marking',
      description: undefined,
      shankDiameter: 25,
      shankLength: 100,
      lengthUnit: undefined,
      isStepped: undefined,
      markingOperations: []
    },
    dimensions: null
  },
  description: [
    LocalizedText {
      locale: 'en',
      text: 'Product definition to use when no marking should be done and the tool should just be transferred to the store pallet without marking.'
    }
  ],
  engineeringUnits: undefined,
  subparameters: undefined
}
```

**Context**

- (X) my request is related to node-opcua acting as an OPCUA CLIENT
- (X ) I have installed node-opcua as a package ( using npm install )

- Device: Laptop
- OS version: Win 11

    - (X) Windows : version : Win 11

- Description of the other OPCUA system I am trying to connect to:

    - Name: Custom

- **node-opcua version:** : 2.130

- **Node:**

  `node --version` = 22.6.0

**Comment by erossignon** [comment]
Closing: fixed in [node-opcua@2.139.0](https://github.com/node-opcua/node-opcua/releases/tag/v2.139.0) and above
