### ISSUE TITLE
Certificate and module not found

### ISSUE THREAD

**Issue by Space69** [node-opcua/node-opcua#160]
Hello everyone,

I am trying to integrate node-opcua to my web based application. I am following the tutorial depicted but I still can't enable the simple_server.

When I try to launche the server thanks to : node bin/simple_server, I can't get rif of this issue.

_AssertionError: fs.existsSync(this.certificateFile), "Certificate file must exist :" + this.certificateFile
   at OPCUAServer.OPCUASecureObject.getCertificateChain (C:\Users\pacesylv\Desktop\tmp\node-opcua\lib\misc\opcua_secure_object.js:61:9)
   at OPCUAServer.OPCUASecureObject.getCertificate (C:\Users\pacesylv\Desktop\tmp\node-opcua\lib\misc\opcua_secure_object.js:48:33)
   at new OPCUAServer (C:\Users\pacesylv\Desktop\tmp\node-opcua\lib\server\opcua_server.js:231:27)
   at Object.<anonymous> (C:\Users\pacesylv\Desktop\tmp\node-opcua\bin\simple_server.js:96:14)
   at Module._compile (module.js:397:26)
   at Object.Module._extensions..js (module.js:404:10)
   at Module.load (module.js:343:32)
   at Function.Module._load (module.js:300:12)
   at Function.Module.runMain (module.js:429:10)
   at startup (node.js:139:18)
   at node.js:999:3_

Even whether I use _npm install _in order to genreate the certificate and everything which I need witinh the project.

My npm version is: 3.3.12. My node js is 5.4.1. I am working on windows 7 and I use a clone of this project in order to integrate it.

By the way, I can have an other issue: _Can't find the module "_auto_generated_DiagnosticInfo"_

Please help me. I am going mad.

Thank you for your kind support.

Best regards

**Comment by Space69** [comment]
This problem comes from windows. The way to solve it is available here:
[https://github.com/node-opcua/node-opcua/issues/160](url)
Thanks you for your great job
