### ISSUE TITLE
Error in lib/xml2json/lib.js

### ISSUE THREAD

**Issue by sandro-k** [node-opcua/node-opcua#209]
Hi,

while running `node-opcua` on Node.js v0.10.40 on an ARMv7 device. I am getting the following error when adding `node-expat` to the `PATH` and starting a OPC-UA Server:

```
30 May 13:25:28 - TypeError: Cannot call method 'join' of undefined
    at ReaderState._on_endElement (/usr/local/node_modules/node-opcua/lib/xml2json/lib.js:135:37)
    at null.<anonymous> (/usr/local/node_modules/node-opcua/lib/xml2json/lib.js:234:28)
    at emit (events.js:95:17)
    at Parser.parse (/usr/local/lib/node_modules/node-expat/lib/node-expat.js:23:22)
    at Parser.write (/usr/local/lib/node_modules/node-expat/lib/node-expat.js:60:19)
    at /usr/local/node_modules/node-opcua/lib/xml2json/lib.js:283:24
    at fs.js:272:14
    at /usr/local/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:42:10
    at Object.oncomplete (fs.js:108:15)
```
When starting the OPC-UA Server without  `node-expat` in the `PATH` it starts up without any issue. 
After changing line 135 to 
```
this.text = ( this.chunks || [] ).join("");
```

I am able to start the OPC-UA Server without any issue and `node-expat` support. Can that be an issue of `node-expat` or is the check in `xml2json` sufficient?

**Comment by sandro-k** [comment]
👍
