### ISSUE TITLE
Application crash due to missing certificate

### ISSUE THREAD

**Issue by jonathanbp** [node-opcua/node-opcua#210]
Hello.

My application would not start due to a missing certificate and produced the following output:

```
/Users/jonathan/Development/Projects/gitlab.com/dice/opc-ua-server.api/node_modules/better-assert/index.js:37
  throw err;
  ^
AssertionError: fs.existsSync(this.certificateFile), "Certificate file must exist :" + this.certificateFile
    at OPCUAServer.OPCUASecureObject.getCertificateChain (/Users/jonathan/Development/Projects/gitlab.com/dice/opc-ua-server.api/node_modules/node-opcua/lib/misc/opcua_secure_object.js:61:9)
    at OPCUAServer.OPCUASecureObject.getCertificate (/Users/jonathan/Development/Projects/gitlab.com/dice/opc-ua-server.api/node_modules/node-opcua/lib/misc/opcua_secure_object.js:48:33)
    at new OPCUAServer (/Users/jonathan/Development/Projects/gitlab.com/dice/opc-ua-server.api/node_modules/node-opcua/lib/server/opcua_server.js:246:27)
    at Object.<anonymous> (/Users/jonathan/Development/Projects/gitlab.com/dice/opc-ua-server.api/build/app.js:9:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
```

It looks like an issue similar to #161 so I followed some of the directions given here, specifically to get the more detailed logs from the `crypto_create_js`:

```
❯ node bin/crypto_create_CA.js
          set OPENSSL_CONF =/Users/jonathan/Development/Projects/gitlab.com/dice/opc-ua-server.api/node_modules/node-opcua/certificates/PKI/CA/conf/caconfig.cnf
        stdout undefined
CA private key already exists ... skipping
 hostname =  vac.local

Create  Application Certificate for Server & its private key
============================================================

 urn =  urn:vac.local:NodeOPCUA-Client
private key  /Users/jonathan/Development/Projects/gitlab.com/dice/opc-ua-server.api/node_modules/node-opcua/certificates/client_key_1024.pem  already exists
    openssl rsa -pubout -in "/Users/jonathan/Development/Projects/gitlab.com/dice/opc-ua-server.api/node_modules/node-opcua/certificates/client_key_1024.pem" > "/Users/jonathan/Development/Projects/gitlab.com/dice/opc-ua-server.api/node_modules/node-opcua/certificates/client_public_key_1024.pub"
        err undefined
private key  /Users/jonathan/Development/Projects/gitlab.com/dice/opc-ua-server.api/node_modules/node-opcua/certificates/client_key_2048.pem  already exists
        certificate /Users/jonathan/Development/Projects/gitlab.com/dice/opc-ua-server.api/node_modules/node-opcua/certificates/client_cert_1024.pem already exists => do not overwrite
          set ALTNAME_URI =urn:vac.local:NodeOPCUA-Client
          set ALTNAME_DNS =localhost
          set ALTNAME_DNS_1 =vac.local

    - the certificate signing request
    ---------------------------------

    openssl req -text  -batch -new -key "/Users/jonathan/Development/Projects/gitlab.com/dice/opc-ua-server.api/node_modules/node-opcua/certificates/client_key_2048.pem" -out "/Users/jonathan/Development/Projects/gitlab.com/dice/opc-ua-server.api/node_modules/node-opcua/certificates/client_cert_2048.pem_csr"

    - then we ask the authority to sign the certificate signing request
    -------------------------------------------------------------------

    openssl ca  -startdate 160605112016Z -enddate 170605112016Z -batch -out "/Users/jonathan/Development/Projects/gitlab.com/dice/opc-ua-server.api/node_modules/node-opcua/certificates/client_cert_2048.pem" -in "/Users/jonathan/Development/Projects/gitlab.com/dice/opc-ua-server.api/node_modules/node-opcua/certificates/client_cert_2048.pem_csr"
        err undefined
        err undefined
        err undefined
        err undefined
        err undefined
        err undefined
        err undefined
        err undefined
        err undefined

    - dump the certificate for a check
    ----------------------------------

    openssl x509 -in "/Users/jonathan/Development/Projects/gitlab.com/dice/opc-ua-server.api/node_modules/node-opcua/certificates/client_cert_2048.pem"  -dates -noout
/Users/jonathan/Development/Projects/gitlab.com/dice/opc-ua-server.api/node_modules/node-opcua/bin/crypto_create_CA.js:309
            process.stdout.write("        out " + line.white.bold + "\n");
                                                            ^

TypeError: Cannot read property 'bold' of undefined
    at LineStream.<anonymous> (/Users/jonathan/Development/Projects/gitlab.com/dice/opc-ua-server.api/node_modules/node-opcua/bin/crypto_create_CA.js:309:61)
    at emitOne (events.js:96:13)
    at LineStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at LineStream.Readable.push (_stream_readable.js:130:10)
    at LineStream.Transform.push (_stream_transform.js:128:32)
    at LineStream._pushBuffer (/Users/jonathan/Development/Projects/gitlab.com/dice/opc-ua-server.api/node_modules/byline/lib/byline.js:123:17)
    at LineStream._transform (/Users/jonathan/Development/Projects/gitlab.com/dice/opc-ua-server.api/node_modules/byline/lib/byline.js:114:8)
    at LineStream.Transform._read (_stream_transform.js:167:10)
    at LineStream.Transform._write (_stream_transform.js:155:12)
```

If I change to code to *not make the white text bold* (see attached [bold.patch.zip](https://github.com/node-opcua/node-opcua/files/300292/bold.patch.zip) file) the process completes successfully, certificates are generated and I can start my application without errors. It seems the problem is in the `colors` library when used on an `undefined` value.

### Environment details:

 * OS: `OSX 10.11.6 Beta (15G7b)`
 * node: `v6.2.1`
 * openssl: `OpenSSL 0.9.8zh 14 Jan 2016`
 * node-opcua: `0.0.54` but same issue in `rev f0b9131` on master branch

**Comment by erossignon** [comment]
This is definitly the same issue as #212  ,and should be fix now
