### ISSUE TITLE
Problems with the weatherstation tutorial

### ISSUE THREAD

**Issue by Alexi16** [node-opcua/node-opcua#220]
I followed all steps of the weatherstation tutorial. Unfortunately it doesn't work. When I try to run the server via 

`$ node weather.js`

I get the following error:
```

C:\Program Files\Git\test\myweatherstation\node_modules\node-opcua\lib\address_space\address_space.js:1339
        throw err;
        ^
 AssertionError: isNonEmptyQualifiedName(options.browseName)
    at C:\Program Files\Git\git_test\myweatherstation\node_modules\node-opcua\lib\address_space\address_space.js:1386:9
    at AddressSpace.modelChangeTransaction (C:\Program Files\Git\git_test\myweatherstation\node_modules\node-opcua\lib\address_space\address_space.js:1336:9)
    at AddressSpace.createNode (C:\Program Files\Git\git_test\myweatherstation\node_modules\node-opcua\lib\address_space\address_space.js:1384:10)
    at AddressSpace.addFolder (C:\Program Files\Git\git_test\myweatherstation\node_modules\node-opcua\lib\address_space\address_space.js:1467:21)
    at create_CityNode (C:\Program Files\Git\git_test\myweatherstation\weather.js:85:39)
    at construct_my_address_space (C:\Program Files\Git\git_test\myweatherstation\weather.js:108:6)
    at post_initialize (C:\Program Files\Git\git_test\myweatherstation\weather.js:122:5)
    at Immediate._onImmediate (C:\Program Files\Git\git_test\myweatherstation\node_modules\node-opcua\lib\server\opcua_server.js:439:9)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

```
What does this AssertionError mean?

**Comment by Alexi16** [comment]
Thank you for you effort, it works now! Very nice example.
