### ISSUE TITLE
Test fail..

### ISSUE THREAD

**Issue by gilesbradshaw** [node-opcua/node-opcua#298]
Are some of the tests indeterminate?

I do

````
$ git clone git://github.com/node-opcua/node-opcua.git
$ cd node-opcua
$ npm install
$ npm test
````

and I now get (I am sure I wasn't before on same commit..)

````

1) TR8 -  disconnecting during connect


  886 passing (1m)
  4 pending
  1 failing

  1) testing ability for client to reconnect when server close connection TR8 -  disconnecting during connect:
     Uncaught AssertionError: expected 0 to be above 2
      at Assertion.fail (node_modules/should/cjs/should.js:231:17)
      at Assertion.value (node_modules/should/cjs/should.js:305:19)
      at test/end_to_end/test_e2e_connection_reconnection.js:1368:49
      at node_modules/async/dist/async.js:3686:9
      at replenish (node_modules/async/dist/async.js:882:17)
      at iterateeCallback (node_modules/async/dist/async.js:867:17)
      at node_modules/async/dist/async.js:840:16
      at node_modules/async/dist/async.js:3691:13
      at apply (node_modules/async/dist/async.js:21:25)
      at node_modules/async/dist/async.js:56:12
      at test/end_to_end/test_e2e_connection_reconnection.js:64:13
      at Timeout._onTimeout (test/end_to_end/test_e2e_connection_reconnection.js:714:13)



npm ERR! Test failed.  See above for more details.


````

**Comment by gilesbradshaw** [comment]
This is something to do with my environment - the connect isn't coming back - if I do

````
var endpointUrl = "opc.tcp://somewhere-far-away.in.an.other.galaxy:thiswontwork";

````

it works...

**Comment by gilesbradshaw** [comment]
If I switch my network off the tests pass..

**Comment by gilesbradshaw** [comment]
Thanks!
