### ISSUE TITLE
client/server default certificates are missing in version 0.1.0-5 

### ISSUE THREAD

**Issue by lucarv** [node-opcua/node-opcua#375]
I have tried to follow the tutorial, and never got very far, I supposed due to "security issues". when following the tutorial steps there is nothing saying one should create the ssl infrastructure with certificates and private keys. 
I did that for the server (just created a self-signed) and copied to where I think it should be, the server works.
but for the client, not so good. I can connect successfully to the server, but I can't create any sessions. I get: 

  ````
      applicationUri = e.tbsCertificate.extensions.subjectAltName.uniformResourceIdentifier[0];
                                                                   ^

TypeError: Cannot read property 'uniformResourceIdentifier' of undefined
    at OPCUAClient._getApplicationUri (C:\Users\lucarv\Documents\dev\node\opcua\opcua-publisher\node_modules\node-opcua-client\src\opcua_client.js:110:68)
    at OPCUAClient.__createSession_step2 (C:\Users\lucarv\Documents\dev\node\opcua\opcua-publisher\node_modules\node-opcua-client\src\opcua_client.js:178:31)
    at OPCUAClient._createSession (C:\Users\lucarv\Documents\dev\node\opcua\opcua-publisher\node_modules\node-opcua-client\src\opcua_client.js:165:10)
    at OPCUAClient.createSession (C:\Users\lucarv\Documents\dev\node\opcua\opcua-publisher\node_modules\node-opcua-client\src\opcua_client.js:584:10)
    at C:\Users\lucarv\Documents\dev\node\opcua\opcua-publisher\routes\index.js:24:18
    at Timeout.delayer [as _onTimeout] (C:\Users\lucarv\Documents\dev\node\opcua\opcua-publisher\node_modules\delayed\delayed.js:27:10)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
```
I suppose it is a certificate issue. any hints (sorry if this is a noob question)

**Comment by erossignon** [comment]
The tutorial works for node-opcua<=0.65 and needs to be updated for new incoming version. Thanks for spotting this. Expecially, there is an extra step required to require the PKI.

**Comment by erossignon** [comment]
This should now be working with the latest version node 0.1.9-6
