### ISSUE TITLE
Constantly update variables inside a loop with a Promise object

### ISSUE THREAD

**Issue by dbporto** [node-opcua/node-opcua#428]
Hello,

I am having a problem on setting up my OPCUA server and due to my current knowledge of JS and NodeJS, I don't know if this a simple problem or not.

My problem is setting a group of objects and variables on OPCUA in a 'for' loop, and when I try to read this variables on UaExpert, they do not update. All the variables that I set outside this loop are read and updated as I need them to be and are 100% functional.

**I'm submitting a ...**  (check one with "x")

 - (x) bug report => (I have looked through https://github.com/node-opcua/node-opcua/issues/82 and https://github.com/node-opcua/node-opcua/issues/142 , those two questions are in line of what I need but they do not solve my problem directly)
 - ( ) feature request
 - ( ) support request 

**Current behavior**
In my NodeJS server, I have a JSON data that is stored in an array: 
> [ {ip: '0.0.0.0', mac: '73:F9:9B', status: 'Connected'},
{ ip: '10.9.1.6', mac: 'F6:13:42', status: 'OK' },
{ ip: '10.9.1.1', mac: '1C:00:4D', status: 'OK'},
{ ip: '10.9.1.5', mac: '8C:04:5D', status: 'Connected' },
{ ip: '10.9.1.2', mac: '6E:0A:D7', status: 'OK' } ]

This data is created from collecting the information from all devices currently on my network, and therefore this list can change throughout the day. To collect the data I use a setInterval() function which updates the value on this JSON data (the 'status' of the device may change during the day, and I use the 'IP' as a reference for each device). 
To create the variables in the server, I use a setTimeout() function to let the setInterval() run the first time in order to assign values to my vars, then, on this setTimeout() function, I iterate on this list through a 'for' loop to add each device to the OPCUA, as can be seen on the following piece of code:
	        	
	       let promises = [];
	       for (i = 0; i < deviceList.length; i++) {
	        	let promise = new Promise(
	        		function (resolve, reject) {
	        			var devicePart = deviceList[i];

	        			newDevice[i] = addressSpace.addObject({
				        	organizedBy: livelistFolder, 
				        	browseName: devicePart.ip
				        });

					 addressSpace.addVariable({
					        componentOf: newDevice[i],
					        browseName: "IP",
					        dataType: "String",
					        value: {
					            get: function () {
					                return new opcua.Variant({dataType: opcua.DataType.String, value: devicePart.ip });
					             }
					         }
					  });
					 addressSpace.addVariable({
					        componentOf: newDevice[i],
					        browseName: "MAC",
					        dataType: "String",
					        value: {
					            get: function () {
					                return new opcua.Variant({dataType: opcua.DataType.String, value: devicePart.mac });
					             }
					         }
					  });

					 addressSpace.addVariable({
					        componentOf: newDevice[i],
					        browseName: "Status",
					        dataType: "String",
					        value: {
					            get: function () {
					                return new opcua.Variant({dataType: opcua.DataType.String, value: devicePart.status });
					             }
					         }
					  });
					 resolve(devicePart);
	        		}
	        	);
	        	promises.push(promise);
	       }
	       Promise.all(promises);

On UaExpert I can see that the device tree is created succesfully, under the folder 'Livelist' and this is what each device looks like:
![screenshot from 2018-02-07 10-45-07](https://user-images.githubusercontent.com/35804542/35917136-1bced95c-0bf4-11e8-8fc7-18894fc92ca7.png)

When the objects and the variables are created, I can see through a simple console.log() on my NodeJS server that all data is being read correctly. 

On Issue #82 there was also a concern with updating the values, and this is my problem here too. If I manually create each device outside the 'for' loop and without a Promise, the values can update. 

  * ( ) I have installed node-opcua from source ( using git clone)
  * (x) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 

    - ( ) Windows : version : _________
    - (x) Linux   : version : Ubuntu 16.04.3 LTS 
    - ( ) MacOs   : version : _________
    - ( ) Raspbian: version : _________
    - ( ) Other   : specify :
   
* **node-opcua version:** ``
0.2.1

* **Node:** 
   `node --version` = 8.9.4

**Issue**

My problem is that my device list can have any number between 3 and 500, which is the highest we registered, and create each device manually would make me write this piece of code 500 times, with some small control to stop writing into the server when I reach my number of devices, since I cannot predict the number of devices when we setup the OPC-UA server.

Using the Promise object allowed me to iterate on the list and assign each object correctly, making me not worry about the deviceList size, and in doing so I avoid writing the same addObject and addVariables 500 times. But in using the Promise object, my variables now do not update.

I am looking for a solution for this problem, either a different way of adding objects and variables so they can update or a setting to allow the variables inside the Promise object to be updated. I do not know if this solution would come from JS, NodeJS or the OPCUA.

Thank you and sorry for the long post.

**Comment by dbporto** [comment]
Since posting this issue I tried to change some logic to try to make this work.

First I tried to create a new function called createDeviceList, and I tried to add the async value to it to see how it behaves:

			async function createDeviceList(deviceList, i) {
        			var devicePart = deviceList[i];

        			newDevice[i] = addressSpace.addObject({
			        	organizedBy: livelistFolder, 
			        	browseName: devicePart.ip
			        });

				 addressSpace.addVariable({
				        componentOf: newDevice[i],
				        browseName: "IP",
				        dataType: "String",
				        value: {
				            get: function () {
				                return new opcua.Variant({dataType: opcua.DataType.String, value: devicePart.ip });
				             }
				         }
				  });
				 addressSpace.addVariable({
				        componentOf: newDevice[i],
				        browseName: "MAC",
				        dataType: "String",
				        value: {
				            get: function () {
				                return new opcua.Variant({dataType: opcua.DataType.String, value: devicePart.mac });
				             }
				         }
				  });

				 addressSpace.addVariable({
				        componentOf: newDevice[i],
				        browseName: "Status",
				        dataType: "String",
				        value: {
				            get: function () {
				                return new opcua.Variant({dataType: opcua.DataType.String, value: devicePart.status });
				             }
				         }
				  });
        		}

And then I tried to iterate on this function with a 'for' loop:

			for (i = 0; i < deviceList.length; i++) {
					createDeviceList(deviceList, i);
			}

But the result is the same as using the Promises.

I also found https://github.com/node-opcua/node-opcua/pull/35 , in which a piece of code is written with the refreshFunc on the value. I tried to implement it and my code looks like this:

	            addressSpace.addVariable({
			            componentOf: deviceList[i],
			            browseName: "Status",
			            dataType: "String",
			            value: {
			            		refreshFunc: function (callback) {
			            			var status = new opcua.Variant({dataType: opcua.DataType.String, value: devicePart.status });

			            			setTimeout(function() {
			            				callback(null, status);
			            			}, 100);
			            		},
			            		set: function(status) {
					                  startAsyncWrite(status,function unused_callback(err,data){});
					        }
			            }
			        });

And this error pops-up:
>/home/dbp/Documents/webmonitor/node_modules/node-opcua-variant/schemas/Variant_schema.js:372
        options.dataType = options.dataType || DataType.Null;
                         ^
TypeError: Cannot create property 'dataType' on string 'OK'
    at Object.construct_hook (/home/dbp/Documents/webmonitor/node_modules/node-opcua-variant/schemas/Variant_schema.js:372:26)
    at new Variant (/home/dbp/Documents/webmonitor/node_modules/node-opcua-variant/_generated_/_auto_generated_Variant.js:48:22)
    at new DataValue /home/dbp/Documents/webmonitor/node_modules/node-opcua-data-value/_generated_/_auto_generated_DataValue.js:58:36)
    at coerceDataValue (/home/dbp/Documents/webmonitor/node_modules/node-opcua-address-space/src/ua_variable.js:946:16)
    at /home/dbp/Documents/webmonitor/node_modules/node-opcua-address-space/src/ua_variable.js:955:25
    at Timeout._onTimeout (/home/dbp/Documents/webmonitor/test.js:371:19)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
