### ISSUE TITLE
Issue with NodeCrawler

### ISSUE THREAD

**Issue by issararab** [node-opcua/node-opcua#597]
**I'm submitting a ...**  (check one with "x")

 - (X ) bug report => search github for a similar issue or PR before submitting
 - ( ) feature request
 - ( ) support request => Please do not submit support request here, instead see use 
      - use [gitter](https://gitter.im/node-opcua/node-opcua) or [stackoverflow](https://stackoverflow.com/questions/tagged/node-opcua) for community support, or 
      - [contact Sterfive for commercial support](https://www.sterfive.com)

**Current behavior**

I was using the "('node-opcua').NodeCrawler" crawler package just fine. I could crawl some of the opcua servers created. However, recently, the lab recently wnats to make a real demo with a small PLC that runs an opcua server from the vendor FESTO and the crawler failed dramatically. I would like to note that the server can be browsed by other tools namely UaExpert and also with a previous implementation of nodejs using client.session.browse() but keeps failing with the NodeCrawler.
  
**Expected behavior**

Bellow is the error i get, it would be much appreciated if this can be solved as soon as possible:
``` 
expecting a known StatusCode but got 0x51d0000
expecting a known StatusCode but got 0x51d0000
expecting a known StatusCode but got 0x51d0000
expecting a known StatusCode but got 0x65000000
expecting a known StatusCode but got 0xa4770000
expecting a known StatusCode but got 0x51d0000
Error: cannot find DataType for encodingByte = 0x35
    at Object.decode (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-variant\schemas\Variant_schema.js:329:19)
    at Variant.decode (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-variant\_generated_\_auto_generated_Variant.js:126:11)
    at Object.decode (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-data-value\schemas\DataValue_schema.js:167:29)
    at DataValue.decode (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-data-value\_generated_\_auto_generated_DataValue.js:122:11)
    at C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-service-read\_generated_\_auto_generated_ReadResponse.js:116:12
    at exports.decodeArray (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-basic-types\src\array.js:38:18)
    at ReadResponse.decode (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-service-read\_generated_\_auto_generated_ReadResponse.js:114:20)
    at MessageBuilder._safe_decode_message_body (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-secure-channel\src\message_builder.js:404:20)
    at MessageBuilder._decode_message_body (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-secure-channel\src\message_builder.js:453:18)
    at MessageBuilderBase._feed_messageChunk (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-transport\src\message_builder_base.js:196:18)
Error: cannot find DataType for encodingByte = 0x35
    at Object.decode (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-variant\schemas\Variant_schema.js:329:19)
    at Variant.decode (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-variant\_generated_\_auto_generated_Variant.js:126:11)
    at Object.decode (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-data-value\schemas\DataValue_schema.js:167:29)
    at DataValue.decode (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-data-value\_generated_\_auto_generated_DataValue.js:122:11)
    at C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-service-read\_generated_\_auto_generated_ReadResponse.js:116:12
    at exports.decodeArray (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-basic-types\src\array.js:38:18)
    at ReadResponse.decode (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-service-read\_generated_\_auto_generated_ReadResponse.js:114:20)
    at MessageBuilder._safe_decode_message_body (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-secure-channel\src\message_builder.js:404:20)
    at MessageBuilder._decode_message_body (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-secure-channel\src\message_builder.js:453:18)
    at MessageBuilderBase._feed_messageChunk (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-transport\src\message_builder_base.js:196:18)
00000000: 01 00 7a 02 dc a4 ec 1d 05 f8 e8 01 14 00 00 00 00 00 00 00 00 ff ff ff ff 00 00 00 5f 00 00 00    ..z.\$l..xh................._...
00000020: 09 11 00 07 84 a7 ec 1d 05 f8 e8 01 0d 07 00 00 00 00 c4 a8 ec 1d 05 f8 e8 01 a6 a8 ec 1d 05 f8    .....'l..xh.......D(l..xh.&(l..x
00000040: e8 01 09 0b 00 00 00 00 00 00 00 00 6e a9 ec 1d 05 f8 e8 01 09 03 01 04 aa ec 1d 05 f8 e8 01 09    h...........n)l..xh.....*l..xh..
00000060: 03 01 08 ab ec 1d 05 f8 e8 01 09 11 00 07 ee ab ec 1d 05 f8 e8 01 0d 07 00 00 00 00 b6 ac ec 1d    ...+l..xh.....n+l..xh.......6,l.
00000080: 05 f8 e8 01 a2 ac ec 1d 05 f8 e8 01 09 0b 00 00 00 00 00 00 00 00 56 ad ec 1d 05 f8 e8 01 09 03    .xh.",l..xh...........V-l..xh...
000000a0: 01 28 b3 ec 1d 05 f8 e8 01 09 03 01 86 b4 ec 1d 05 f8 e8 01 09 11 00 07 6c b5 ec 1d 05 f8 e8 01    .(3l..xh.....4l..xh.....l5l..xh.
000000c0: 0d 07 00 00 00 00 52 b6 ec 1d 05 f8 e8 01 3e b6 ec 1d 05 f8 e8 01 09 0b 00 00 00 00 00 00 00 00    ......R6l..xh.>6l..xh...........
000000e0: 06 b7 ec 1d 05 f8 e8 01 09 03 01 92 b7 ec 1d 05 f8 e8 01 09 03 01 64 b8 ec 1d 05 f8 e8 01 09 11    .7l..xh.....7l..xh....d8l..xh...
00000100: 00 07 2c b9 ec 1d 05 f8 e8 01 0d 07 00 00 00 00 f4 b9 ec 1d 05 f8 e8 01 e0 b9 ec 1d 05 f8 e8 01    ..,9l..xh.......t9l..xh.`9l..xh.
00000120: 09 0b 00 00 00 00 00 00 00 00 8a ba ec 1d 05 f8 e8 01 09 03 01 0c bb ec 1d 05 f8 e8 01 09 03 01    ...........:l..xh.....;l..xh....
00000140: ca bb ec 1d 05 f8 e8 01 09 11 00 07 7e bc ec 1d 05 f8 e8 01 0d 07 00 00 00 00 32 bd ec 1d 05 f8    J;l..xh.....~<l..xh.......2=l..x
00000160: e8 01 1e bd ec 1d 05 f8 e8 01 09 0b 00 00 00 00 00 00 00 00 c8 bd ec 1d 05 f8 e8 01 09 03 01 4a    h..=l..xh...........H=l..xh....J
00000180: be ec 1d 05 f8 e8 01 09 03 01 fe be ec 1d 05 f8 e8 01 09 11 00 07 b2 bf ec 1d 05 f8 e8 01 0d 07    >l..xh....~>l..xh.....2?l..xh...
000001a0: 00 00 00 00 70 c0 ec 1d 05 f8 e8 01 5c c0 ec 1d 05 f8 e8 01 09 0b 00 00 00 00 00 00 00 00 06 c1    ....p@l..xh.\@l..xh............A
000001c0: ec 1d 05 f8 e8 01 09 03 01 88 c1 ec 1d 05 f8 e8 01 09 03 01 46 c2 ec 1d 05 f8 e8 01 09 11 00 07    l..xh.....Al..xh....FBl..xh.....
000001e0: fa c2 ec 1d 05 f8 e8 01 0d 07 00 00 00 00 c2 c3 ec 1d 05 f8 e8 01 a4 c3 ec 1d 05 f8 e8 01 09 0b    zBl..xh.......BCl..xh.$Cl..xh...
00000200: 00 00 00 00 00 00 00 00 58 c4 ec 1d 05 f8 e8 01 09 03 01 e4 c4 ec 1d 05 f8 e8 01 09 03 01 b6 c5    ........XDl..xh....dDl..xh....6E
00000220: ec 1d 05 f8 e8 01 09 11 00 07 56 c6 ec 1d 05 f8 e8 01 0d 07 00 00 00 00 1e c7 ec 1d 05 f8 e8 01    l..xh.....VFl..xh........Gl..xh.
00000240: 0a c7 ec 1d 05 f8 e8 01 09 0b 00 00 00 00 00 00 00 00 aa c7 ec 1d 05 f8 e8 01 09 03 01 40 c8 ec    .Gl..xh...........*Gl..xh....@Hl
00000260: 1d 05 f8 e8 01 09 03 01 fe c8 ec 1d 05 f8 e8 01 09 11 01 00 28 01 b2 c9 ec 1d 05 f8 e8 01 0d 96    ..xh....~Hl..xh.....(.2Il..xh...
00000280: 02 00 00 00 01 00 2a 01 01 1c 00 00 00 0d 00 00 00 53 65 72 76 65 72 48 61 6e 64 6c 65 73 00 07    ......*..........ServerHandles..
000002a0: 01 00 00 00 00 00 00 00 00 01 00 2a 01 01 1c 00 00 00 0d 00 00 00 43 6c 69 65 6e 74 48 61 6e 64    ...........*..........ClientHand
000002c0: 6c 65 73 00 07 01 00 00 00 00 00 00 00 00 7a ca ec 1d 05 f8 e8 01 66 ca ec 1d 05 f8 e8 01 09 0b    les...........zJl..xh.fJl..xh...
000002e0: 00 00 00 00 00 00 00 00 b4 cc ec 1d 05 f8 e8 01 09 03 01 40 cd ec 1d 05 f8 e8 01 09 03 01 08 ce    ........4Ll..xh....@Ml..xh.....N
00000300: ec 1d 05 f8 e8 01 09 11 01 00 28 01 bc ce ec 1d 05 f8 e8 01 0d 96 01 00 00 00 01 00 2a 01 01 1d    l..xh.....(.<Nl..xh.........*...
00000320: 00 00 00 0e 00 00 00 53 75 62 73 63 72 69 70 74 69 6f 6e 49 64 00 07 ff ff ff ff 00 00 00 00 00    .......SubscriptionId...........
00000340: 8e cf ec 1d 05 f8 e8 01 7a cf ec 1d 05 f8 e8 01 09 0b 00 00 00 00 00 00 00 00 c4 d0 ec 1d 05 f8    .Ol..xh.zOl..xh...........DPl..x
00000360: e8 01 09 03 01 5a d1 ec 1d 05 f8 e8 01 09 03 01 2c d2 ec 1d 05 f8 e8 01 09 11 00 05 ea d2 ec 1d    h....ZQl..xh....,Rl..xh.....jRl.
00000380: 05 f8 e8 01 0d 05 05 00 52 67 77 a4 fc f7 e8 01 9e d3 ec 1d 05 f8 e8 01 09 0b 00 00 00 00 00 00    .xh.....Rgw$|wh..Sl..xh.........
000003a0: 00 00 34 d4 ec 1d 05 f8 e8 01 09 03 01 c0 d4 ec 1d 05 f8 e8 01 09 03 01 88 d5 ec 1d 05 f8 e8 01    ..4Tl..xh....@Tl..xh.....Ul..xh.
000003c0: 09 11 00 0b 32 d6 ec 1d 05 f8 e8 01 0d 16 00 00 01 08 00 00 00 00 00 00 00 00 00 49 40 ba 6d 77    ....2Vl..xh................I@:mw
000003e0: a4 fc f7 e8 01 d2 d6 ec 1d 05 f8 e8 01 09 0b 00 00 00 00 00 00 00 00 ae d7 ec 1d 05 f8 e8 01 09    $|wh.RVl..xh............Wl..xh..

 .... ( 1887)
  message(ReadResponse)                                                                                                             |
    responseHeader(ResponseHeader)                                                                                                  |
    .timeStamp : UtcTime                                                                                                            |
     Fri Feb 20 2037 21:42:29 GMT+0100 (Central European Standard Time)                                                             |s:4    e:12   n:8    dca4ec1d05f8e801
    .requestHandle : IntegerId                                                                                                      |
     20                                                                                                                             |s:12   e:16   n:4    14000000
    .serviceResult : StatusCode                                                                                                     |
     0                                                                                                                              |s:16   e:20   n:4    00000000
      serviceDiagnostics(DiagnosticInfo)                                                                                            |
      .encodingByte : Mask                                                                                                          |
       0x0                                                                                                                          |s:20   e:21   n:1    00
        012345678                                                                                                                   |s:20   e:21   n:1    00
        n........  <- has SymbolicId
        .n.......  <- has NamespaceUri
        ..n......  <- has LocalizedText
        ...n.....  <- has Locale
        ....n....  <- has AdditionalInfo
        .....n...  <- has InnerStatusCode
        ......n..  <- has InnerDiagnosticInfo
    .stringTable (length = 0) [                                                                                                     |s:21   e:25   n:4    ffffffff
    ] // stringTable                                                                                                                |
    .additionalHeader : ExtensionObject                                                                                             |
     null                                                                                                                           |s:25   e:28   n:3    000000
  .results (length = 95) [                                                                                                          |s:28   e:32   n:4    5f000000
     #0 {                                                                                                                           |
      .encodingByte : Mask                                                                                                          |
       0x9                                                                                                                          |s:32   e:33   n:1    09
        012345678                                                                                                                   |s:32   e:33   n:1    09
        Y........  <- has Value
        .n.......  <- has StatusCode
        ..n......  <- has SourceTimestamp
        ...Y.....  <- has ServerTimestamp
        ....n....  <- has SourcePicoseconds
        .....n...  <- has ServerPicoseconds
      dataType:    NodeId                                                                                                           |
      isArray:     false                                                                                                            |
      dimension:   false                                                                                                            |
      .Variant : NodeId                                                                                                             |
       ns=0;i=7                                                                                                                     |s:34   e:36   n:2    0007
      .serverTimestamp : DateTime                                                                                                   |
       Fri Feb 20 2037 21:42:29 GMT+0100 (Central European Standard Time)                                                           |s:36   e:44   n:8    84a7ec1d05f8e801
     } // # 0                                                                                                                       |
     #1 {                                                                                                                           |
      .encodingByte : Mask                                                                                                          |
       0xd                                                                                                                          |s:44   e:45   n:1    0d
        012345678                                                                                                                   |s:44   e:45   n:1    0d
        Y........  <- has Value
        .n.......  <- has StatusCode
        ..Y......  <- has SourceTimestamp
        ...Y.....  <- has ServerTimestamp
        ....n....  <- has SourcePicoseconds
        .....n...  <- has ServerPicoseconds
      dataType:    UInt32                                                                                                           |
      isArray:     false                                                                                                            |
      dimension:   false                                                                                                            |
      .Variant : UInt32                                                                                                             |
       0                                                                                                                            |s:46   e:50   n:4    00000000
 Error in  TypeError: ec.decodeHighPrecisionDateTime is not a function
    at Object.decode_debug (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-data-value\schemas\DataValue_schema.js:130:45)
    at DataValue.decode_debug (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-data-value\_generated_\_auto_generated_DataValue.js:125:11)
    at _decode_member_ (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-factory\src\factories_baseobject.js:119:15)
    at ReadResponse.BaseUAObject.decode_debug (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-factory\src\factories_baseobject.js:155:17)
    at packet_analyzer (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-packet-analyzer\src\packet_analyzer\packet_analyzer.js:198:20)
    at MessageBuilder._safe_decode_message_body (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-secure-channel\src\message_builder.js:410:9)
    at MessageBuilder._decode_message_body (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-secure-channel\src\message_builder.js:453:18)
    at MessageBuilderBase._feed_messageChunk (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-transport\src\message_builder_base.js:196:18)
    at PacketAssembler.<anonymous> (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-transport\src\message_builder_base.js:53:14)
    at PacketAssembler.emit (events.js:189:13)
 Error in  TypeError: ec.decodeHighPrecisionDateTime is not a function
    at Object.decode_debug (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-data-value\schemas\DataValue_schema.js:130:45)
    at DataValue.decode_debug (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-data-value\_generated_\_auto_generated_DataValue.js:125:11)
    at _decode_member_ (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-factory\src\factories_baseobject.js:119:15)
    at ReadResponse.BaseUAObject.decode_debug (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-factory\src\factories_baseobject.js:155:17)
    at packet_analyzer (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-packet-analyzer\src\packet_analyzer\packet_analyzer.js:198:20)
    at MessageBuilder._safe_decode_message_body (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-secure-channel\src\message_builder.js:410:9)
    at MessageBuilder._decode_message_body (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-secure-channel\src\message_builder.js:453:18)
    at MessageBuilderBase._feed_messageChunk (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-transport\src\message_builder_base.js:196:18)
    at PacketAssembler.<anonymous> (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-transport\src\message_builder_base.js:53:14)
    at PacketAssembler.emit (events.js:189:13)
 objMessage  ReadResponse {
  responseHeader:
   ResponseHeader {
     timeStamp: 2019-02-20T17:05:43.403Z,
     requestHandle: 4294967295,
     serviceResult:
      ConstantStatusCode { value: 0, description: 'No Error', name: 'Good' },
     serviceDiagnostics:
      DiagnosticInfo {
        namespaceUri: -1,
        symbolicId: -1,
        locale: -1,
        localizedText: -1,
        additionalInfo: null,
        innerStatusCode: [ConstantStatusCode],
        innerDiagnosticInfo: null },
     stringTable: [],
     additionalHeader: null },
  results: [],
  diagnosticInfos: [] }
 ---------------- block
 ---------------- chunk i= 0
00000000: 4d 53 47 46 77 07 00 00 13 00 00 00 18 00 00 00 0f 00 00 00 14 00 00 00 01 00 7a 02 dc a4 ec 1d    MSGFw.....................z.\$l.
00000020: 05 f8 e8 01 14 00 00 00 00 00 00 00 00 ff ff ff ff 00 00 00 5f 00 00 00 09 11 00 07 84 a7 ec 1d    .xh................._........'l.
00000040: 05 f8 e8 01 0d 07 00 00 00 00 c4 a8 ec 1d 05 f8 e8 01 a6 a8 ec 1d 05 f8 e8 01 09 0b 00 00 00 00    .xh.......D(l..xh.&(l..xh.......
00000060: 00 00 00 00 6e a9 ec 1d 05 f8 e8 01 09 03 01 04 aa ec 1d 05 f8 e8 01 09 03 01 08 ab ec 1d 05 f8    ....n)l..xh.....*l..xh.....+l..x
00000080: e8 01 09 11 00 07 ee ab ec 1d 05 f8 e8 01 0d 07 00 00 00 00 b6 ac ec 1d 05 f8 e8 01 a2 ac ec 1d    h.....n+l..xh.......6,l..xh.",l.
000000a0: 05 f8 e8 01 09 0b 00 00 00 00 00 00 00 00 56 ad ec 1d 05 f8 e8 01 09 03 01 28 b3 ec 1d 05 f8 e8    .xh...........V-l..xh....(3l..xh
000000c0: 01 09 03 01 86 b4 ec 1d 05 f8 e8 01 09 11 00 07 6c b5 ec 1d 05 f8 e8 01 0d 07 00 00 00 00 52 b6    .....4l..xh.....l5l..xh.......R6
000000e0: ec 1d 05 f8 e8 01 3e b6 ec 1d 05 f8 e8 01 09 0b 00 00 00 00 00 00 00 00 06 b7 ec 1d 05 f8 e8 01    l..xh.>6l..xh............7l..xh.
00000100: 09 03 01 92 b7 ec 1d 05 f8 e8 01 09 03 01 64 b8 ec 1d 05 f8 e8 01 09 11 00 07 2c b9 ec 1d 05 f8    ....7l..xh....d8l..xh.....,9l..x
00000120: e8 01 0d 07 00 00 00 00 f4 b9 ec 1d 05 f8 e8 01 e0 b9 ec 1d 05 f8 e8 01 09 0b 00 00 00 00 00 00    h.......t9l..xh.`9l..xh.........
00000140: 00 00 8a ba ec 1d 05 f8 e8 01 09 03 01 0c bb ec 1d 05 f8 e8 01 09 03 01 ca bb ec 1d 05 f8 e8 01    ...:l..xh.....;l..xh....J;l..xh.
00000160: 09 11 00 07 7e bc ec 1d 05 f8 e8 01 0d 07 00 00 00 00 32 bd ec 1d 05 f8 e8 01 1e bd ec 1d 05 f8    ....~<l..xh.......2=l..xh..=l..x
00000180: e8 01 09 0b 00 00 00 00 00 00 00 00 c8 bd ec 1d 05 f8 e8 01 09 03 01 4a be ec 1d 05 f8 e8 01 09    h...........H=l..xh....J>l..xh..
000001a0: 03 01 fe be ec 1d 05 f8 e8 01 09 11 00 07 b2 bf ec 1d 05 f8 e8 01 0d 07 00 00 00 00 70 c0 ec 1d    ..~>l..xh.....2?l..xh.......p@l.
000001c0: 05 f8 e8 01 5c c0 ec 1d 05 f8 e8 01 09 0b 00 00 00 00 00 00 00 00 06 c1 ec 1d 05 f8 e8 01 09 03    .xh.\@l..xh............Al..xh...
000001e0: 01 88 c1 ec 1d 05 f8 e8 01 09 03 01 46 c2 ec 1d 05 f8 e8 01 09 11 00 07 fa c2 ec 1d 05 f8 e8 01    ..Al..xh....FBl..xh.....zBl..xh.
00000200: 0d 07 00 00 00 00 c2 c3 ec 1d 05 f8 e8 01 a4 c3 ec 1d 05 f8 e8 01 09 0b 00 00 00 00 00 00 00 00    ......BCl..xh.$Cl..xh...........
00000220: 58 c4 ec 1d 05 f8 e8 01 09 03 01 e4 c4 ec 1d 05 f8 e8 01 09 03 01 b6 c5 ec 1d 05 f8 e8 01 09 11    XDl..xh....dDl..xh....6El..xh...
00000240: 00 07 56 c6 ec 1d 05 f8 e8 01 0d 07 00 00 00 00 1e c7 ec 1d 05 f8 e8 01 0a c7 ec 1d 05 f8 e8 01    ..VFl..xh........Gl..xh..Gl..xh.
00000260: 09 0b 00 00 00 00 00 00 00 00 aa c7 ec 1d 05 f8 e8 01 09 03 01 40 c8 ec 1d 05 f8 e8 01 09 03 01    ..........*Gl..xh....@Hl..xh....
00000280: fe c8 ec 1d 05 f8 e8 01 09 11 01 00 28 01 b2 c9 ec 1d 05 f8 e8 01 0d 96 02 00 00 00 01 00 2a 01    ~Hl..xh.....(.2Il..xh.........*.
000002a0: 01 1c 00 00 00 0d 00 00 00 53 65 72 76 65 72 48 61 6e 64 6c 65 73 00 07 01 00 00 00 00 00 00 00    .........ServerHandles..........
000002c0: 00 01 00 2a 01 01 1c 00 00 00 0d 00 00 00 43 6c 69 65 6e 74 48 61 6e 64 6c 65 73 00 07 01 00 00    ...*..........ClientHandles.....
000002e0: 00 00 00 00 00 00 7a ca ec 1d 05 f8 e8 01 66 ca ec 1d 05 f8 e8 01 09 0b 00 00 00 00 00 00 00 00    ......zJl..xh.fJl..xh...........
00000300: b4 cc ec 1d 05 f8 e8 01 09 03 01 40 cd ec 1d 05 f8 e8 01 09 03 01 08 ce ec 1d 05 f8 e8 01 09 11    4Ll..xh....@Ml..xh.....Nl..xh...
00000320: 01 00 28 01 bc ce ec 1d 05 f8 e8 01 0d 96 01 00 00 00 01 00 2a 01 01 1d 00 00 00 0e 00 00 00 53    ..(.<Nl..xh.........*..........S
00000340: 75 62 73 63 72 69 70 74 69 6f 6e 49 64 00 07 ff ff ff ff 00 00 00 00 00 8e cf ec 1d 05 f8 e8 01    ubscriptionId............Ol..xh.
00000360: 7a cf ec 1d 05 f8 e8 01 09 0b 00 00 00 00 00 00 00 00 c4 d0 ec 1d 05 f8 e8 01 09 03 01 5a d1 ec    zOl..xh...........DPl..xh....ZQl
00000380: 1d 05 f8 e8 01 09 03 01 2c d2 ec 1d 05 f8 e8 01 09 11 00 05 ea d2 ec 1d 05 f8 e8 01 0d 05 05 00    ..xh....,Rl..xh.....jRl..xh.....
000003a0: 52 67 77 a4 fc f7 e8 01 9e d3 ec 1d 05 f8 e8 01 09 0b 00 00 00 00 00 00 00 00 34 d4 ec 1d 05 f8    Rgw$|wh..Sl..xh...........4Tl..x
000003c0: e8 01 09 03 01 c0 d4 ec 1d 05 f8 e8 01 09 03 01 88 d5 ec 1d 05 f8 e8 01 09 11 00 0b 32 d6 ec 1d    h....@Tl..xh.....Ul..xh.....2Vl.
000003e0: 05 f8 e8 01 0d 16 00 00 01 08 00 00 00 00 00 00 00 00 00 49 40 ba 6d 77 a4 fc f7 e8 01 d2 d6 ec    .xh................I@:mw$|wh.RVl

 .... ( 1911)
cannot decode message  for valid object of type ns=0;i=634 ReadResponse
 Timeout .... waiting for response for  ReadRequest { /*RequestHeader*/
 authenticationToken           /* NodeId                           */: ns=1;g=3992C587-5932-8A70-4B64-063005F0CFCC
 timeStamp                     /* UtcTime                          */: 2019-02-20T17:05:43.391Z
 requestHandle                 /* IntegerId                        */: 20               0x14
 returnDiagnostics             /* UInt32                           */: 0               0x0
 auditEntryId                  /* UAString                         */:
 timeoutHint                   /* UInt32                           */: 0               0x0
 additionalHeader              /* ExtensionObject                  */: null
};
ns=0;i=2287 bn= SecurityRejectedRequestsCount class = Variable ns=0;i=63
#_reconstruct_manageable_object: Cannot find reference ns=0;i=2287 in cache
C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-client-crawler\src\node_crawler.js:1008
                reference.nodeClass = ref.$nodeClass;
                                    ^

TypeError: Cannot set property 'nodeClass' of undefined
    at C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-client-crawler\src\node_crawler.js:1008:37
    at Array.map (<anonymous>)
    at _reconstruct_manageable_object (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-client-crawler\src\node_crawler.js:991:31)
    at Object.func (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-client-crawler\src\node_crawler.js:930:21)
    at Immediate.<anonymous> (C:\Users\issar\OneDrive\Desktop\fc\Stefan_Reitmayer-step-design\Node-Client\node_modules\node-opcua-client-crawler\src\node_crawler.js:917:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
``` 
**Minimal reproduction of the problem with instructions**

  1. ________________
  2. ________________
  3. ________________
  ...
  
**What is the motivation / use case for changing the behavior?**

I know that the PLC was coded using 4diag, a tool used to develop distributed PLCs. and the opcua server used in the PLC in question make use of "open62541." a C implemetation of opcua that you can find its implementation in Git.
 
**Please tell us about your environment:**

  * (X ) my request is related to node-opcua acting as a  OPCUA CLIENT 
  * ( )  my request is related to node-opcua acting as a OPCUA SERVER 

  * ( ) I have installed node-opcua from source ( using git clone)
  * (X) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: __ASUSZenBook 2018___
  * OS version: __Windows 10___
    
    - (X) Windows : version : ____10_____
    - ( ) Linux   : version : _________
    - ( ) MacOs   : version : _________
    - ( ) Raspbian: version : _________
    - ( ) Other   : specify :
   
   * Description of the other OPCUA system I am trying to connect to:
   
     - Name:_________
     - Version:_________
     - Manufacturer/Software vendor:____FESTO_____
     - link : https://
     
    
* **node-opcua version:**  :

* **Node:** 
   `node --version` = latest version

**Comment by erossignon** [comment]
How could we get access to the Festo device for testing purpose ?
