### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by eg-be** [node-opcua/node-opcua#646]
**I'm submitting a bug report**

**Current behavior**
From time to time, I am getting an error when running an opcua-server based on node-opcua: 

```
18.07.2019 13:39:36 error: uncaughtException: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at add_all_in (E:\snapshot\SimulationServer\node_modules\node-opcua-server\dist\server_subscription.js:1177:26)
    at Subscription._collectNotificationData (E:\snapshot\SimulationServer\node_modules\node-opcua-server\dist\server_subscription.js:1103:13)
    at Subscription._harvestMonitoredItems (E:\snapshot\SimulationServer\node_modules\node-opcua-server\dist\server_subscription.js:1140:39)

    at Subscription.process_subscription (E:\snapshot\SimulationServer\node_modules\node-opcua-server\dist\server_subscription.js:788:18)
    at Subscription._tick (E:\snapshot\SimulationServer\node_modules\node-opcua-server\dist\server_subscription.js:917:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
18.07.2019 13:39:36 error: uncaughtException: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at add_all_in (E:\snapshot\SimulationServer\node_modules\node-opcua-server\dist\server_subscription.js:1177:26)
    at Subscription._collectNotificationData (E:\snapshot\SimulationServer\node_modules\node-opcua-server\dist\server_subscription.js:1103:13)
    at Subscription._harvestMonitoredItems (E:\snapshot\SimulationServer\node_modules\node-opcua-server\dist\server_subscription.js:1140:39)

    at Subscription.process_subscription (E:\snapshot\SimulationServer\node_modules\node-opcua-server\dist\server_subscription.js:788:18)
    at Subscription._tick (E:\snapshot\SimulationServer\node_modules\node-opcua-server\dist\server_subscription.js:917:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[...]
```
The message is repeated 132 times.

As the stack is pointing towards some internal sources of node-opcua, I suspect something is going wrong inside node-opcua.

**Minimal reproduction of the problem with instructions**
The problem occurs rarely on a random basis. It seems it is more likely to happen if multiple clients connect and disconnect to the opcua-server within a short manner of time. But it can also happen if only one client is connected to the node-opcua server.
Sometimes it happens immediately after the only one client has connected, sometimes the server runs for some minutes and the error occurs. Sometimes the server runs for ages without any problem at all.

The server where the problem occurred right now (where I was able to capture a stack) has 11 subscriptions, where each subscription holds between 4 and 294 opcua-variables. I doubt that it is related to the number of subscriptions or size of a subscription, as it happened before with other configurations (but I was unable to get a stack then). All Subscriptions use a PublishingInterval of 500ms.

The problem occurs without the client is required to write anything onto the server.

**Please tell us about your environment:**
  * (x)  my request is related to node-opcua acting as a OPCUA SERVER 
  * (x) I have installed node-opcua as a package ( using npm install )
  * (x ) Windows : version : 7

Connecting to the  node OPCUA SERVER using either UAExpert, or from our custom client (which is based on the OPC UA Client/Server SDK from Unified Automation),   
        
* **node-opcua version:**  :
   `npm list node-opcua` = -- node-opcua@2.1.0

* **Node:** 
   `node --version` =v12.6.0

**Comment by eg-be** [comment]
Maybe this issue is not related to node-opcua at all, but rather to pkg?
https://github.com/zeit/pkg/issues/681
I'm trying to reproduce the problem with a non-packaged application using node-opuca, but did not have any success so far..

**Comment by eg-be** [comment]
No way to reproduce it without using a packaged application. Guess this has nothing to do with node-opcua, sorry.
