### ISSUE TITLE
diferent behavior for sample_client.js versus sample_client_ts.ts

### ISSUE THREAD

**Issue by bcatalin** [node-opcua/node-opcua#675]
**I'm submitting a ...**  (check one with "x")

 - (x) bug report => search github for a similar issue or PR before submitting
 - ( ) feature request
 - ( ) support request => Please do not submit support request here, instead see use 
      - use [gitter](https://gitter.im/node-opcua/node-opcua) or [stackoverflow](https://stackoverflow.com/questions/tagged/node-opcua) for community support, or 
      - [contact Sterfive for commercial support](https://www.sterfive.com)

**Current behavior**

sample_client.js has a different behavior compared with sample_client_ts.ts using the same OPC-UA server and the same node id. 
The output is:
sample_client.js 
connected !
Browsing rootfolder: 
Objects ns=0;i=85
Types ns=0;i=86
Views ns=0;i=87
 4.1 free mem % =  DataValue:
   value:           Variant(Scalar<Float>, value: 66)
   statusCode:      Good (0x00000)
   serverTimestamp: null
   sourceTimestamp: null
 4.2 free mem % =  DataValue:
   value:           Variant(Scalar<Float>, value: 66)
   statusCode:      Good (0x00000)
   serverTimestamp: 2012-01-05T09:17:44.832Z $ 491.100.000
   sourceTimestamp: 2012-01-05T09:17:44.832Z $ 491.100.000
-------------------------------------
/home/pi/tmp/playground/fromMyServer/sample_client.js:120
       monitoredItem.on("changed", function(dataValue) {
                     ^

TypeError: monitoredItem.on is not a function
    at /home/pi/tmp/playground/fromMyServer/sample_client.js:120:22
    at /home/pi/tmp/playground/fromMyServer/node_modules/async/dist/async.js:2952:28

Looks like the ClientSubscription class is changed ?

**Expected behavior**

both files should produce the same output with the same inputs.

**Minimal reproduction of the problem with instructions**

  1. Start sample_client_ts.ts and monitor some data. Working....
  2. Start sample_client.js and monitor the same data. Is not working....
 
  ...
  
**What is the motivation / use case for changing the behavior?**
TypeScript and Javascript should be the same

**Please tell us about your environment:**

  * (x) my request is related to node-opcua acting as a  OPCUA CLIENT 
  * ( )  my request is related to node-opcua acting as a OPCUA SERVER 

  * ( ) I have installed node-opcua from source ( using git clone)
  * (x) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: RPi4
  * OS version: Raspbian 10
    
    - ( ) Windows : version : _________
    - ( ) Linux   : version : _________
    - ( ) MacOs   : version : _________
    - (x) Raspbian: version : 10 (buster)
    - ( ) Other   : specify :
   
   * Description of the other OPCUA system I am trying to connect to:
   
     - Name:___S7_____
     - Version:___1500______
     - Manufacturer/Software vendor:____Siemens_____
     - link : https://
     
    
* **node-opcua version:**  :

2.1.8
* **Node:** 
   `node --version` =12.8.0

**Comment by bcatalin** [comment]
Who has the same issue, please check https://github.com/node-opcua/node-opcua/wiki/2.0.0-breaking-changes
and adapt the code accordingly.
