### ISSUE TITLE
Invalid variant on boolean

### ISSUE THREAD

**Issue by bruegth** [node-opcua/node-opcua#684]
**I'm submitting a ...**  (check one with "x")

 - (x) bug report
 - ( ) feature request
 - ( ) support request

**Current behavior**
```
Error: Invalid variant arrayType: 0  dataType: 1 value:true
    at constructHook (/app/node_modules/node-opcua-variant/dist/variant.js:389:19)
    at new Variant (/app/node_modules/node-opcua-variant/dist/variant.js:48:19)
    at VariableHandler.handleGet (/app/out/opcua/VariableHandler.js:183:28)
    at UAVariable.timestamped_get [as refreshFunc] (/app/out/opcua/AddressSpaceBuilderForProcessVariable.js:214:50)
    at UAVariable.asyncRefresh (/app/node_modules/node-opcua-address-space/dist/src/ua_variable.js:306:26)
    at UAVariable.asyncRefresh (eval at thenify.withCallback (/app/node_modules/thenify/index.js:33:10), <anonymous>:6:48)
    at UAVariable.readValueAsync (/app/node_modules/node-opcua-address-space/dist/src/ua_variable.js:813:18)
    at UAVariable.readValueAsync (eval at thenify.withCallback (/app/node_modules/thenify/index.js:33:10), <anonymous>:6:48)
    at monitoredItem_read_and_record_value_async (/app/node_modules/node-opcua-server/dist/opcua_server.js:228:10)
    at MonitoredItem.samplingFunc (/app/node_modules/node-opcua-server/dist/opcua_server.js:256:13)
    at MonitoredItem._on_sampling_timer (/app/node_modules/node-opcua-server/dist/monitored_item.js:452:31)
    at Immediate.setImmediate [as _onImmediate] (/app/node_modules/node-opcua-server/dist/node_sampler.js:15:24)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5) {}
```

**Expected behavior**

**Please tell us about your environment:**
Docker image node:10
node-opcua: 2.1.8
  * ( ) my request is related to node-opcua acting as a  OPCUA CLIENT 
  * (x)  my request is related to node-opcua acting as a OPCUA SERVER 

  * ( ) I have installed node-opcua from source ( using git clone)
  * (x) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua

**Comment by erossignon** [comment]
Please make sure all your node-opcua-xxx packages in packages.json relates to same version.
Use `npx npm-check-updates -u` to update package version consistently.

**Comment by bruegth** [comment]
You are right, it was a wrong JSON conversion for boolean. Sorry for the circumstances.
