### ISSUE TITLE
Graceful shutdown of Monitored items and Subscriptions

### ISSUE THREAD

**Issue by MattsNorrbohm** [node-opcua/node-opcua#686]
**I'm submitting a - (x) bug report => search github for a similar issue or PR before submitting

**Current behavior**
When I for all of my monitored items call first the montitoredItem.terminate() and when these are all done then call subscription.terminate() I get the following errors:

```javascript
(node:9008) UnhandledPromiseRejectionWarning: Error
    at Object.assert (c:\Projects\....\node_modules\node-opcua-assert\source\index.ts:12:21)
    at ClientSubscriptionImpl._delete_monitored_items (c:\Projects\....\node_modules\node-opcua-client\source\private\client_subscription_impl.ts:296:9)
    at ClientMonitoredItemImpl.terminate (c:\Projects\....\node_modules\node-opcua-client\source\private\client_monitored_item_impl.ts:83:22)
    at eval (eval at thenify.withCallback (c:\Projects\....\node_modules\thenify\index.js:33:10), <anonymous>:12:12)
    at new Promise (<anonymous>)
    at ClientMonitoredItemImpl.terminate (eval at thenify.withCallback (c:\Projects\....\node_modules\thenify\index.js:33:10), <anonymous>:10:8)
    at Timeout.monClear [as _onTimeout] (c:\Projects\....\umtest.js:37:82)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
warning.js:18
(node:9008) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
warning.js:18
(node:9008) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

umtest.js line 37:82 is where I call the subscription.terminate()
```
**Expected behavior**
No error, no monitored items in the list should not generate any errors when calling subscription.terminate(). 

**Minimal reproduction of the problem with instructions**
  1. Set up a subscription with a monitored item.
  2. Terminate the monitored item by calling monitoredItem.terminate()
  3. When step 2 is done, call subscription.terminate()

if step 2 is skipped no error is thrown.
  
**What is the motivation / use case for changing the behavior?**
Best practices to close down a connection to a OPC UA server.

**Please tell us about your environment:**
  * (x ) my request is related to node-opcua acting as a  OPCUA CLIENT 
  * ( )  my request is related to node-opcua acting as a OPCUA SERVER 

  * ( ) I have installed node-opcua from source ( using git clone)
  * ( x) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: ? Dell Laptop?
  * OS version: 
    
    - (x) Windows : version : 10 Enterprise latest patches/SP
    - ( ) Linux   : version : _________
    - ( ) MacOs   : version : _________
    - ( ) Raspbian: version : _________
    - ( ) Other   : specify :
   
   * Description of the other OPCUA system I am trying to connect to:
   
??
     
* **node-opcua version:**  :
2.1.9

* **Node:** 
v10.15.1

**Comment by erossignon** [comment]
Hi @MattsNorrbohm , 
The error is an assert that verify that the underlying subscription is still valid when the monitoredItem is deleted, 

Just to make sure  and because there are several ways of creation subscription and monitored item, can you provide a minimal gist that demonstrate the issue ?
- create a connection & session
- create subscription
- add some monitored Item
- delete the monitored Item
- delete subscription
- close session & connection

**Comment by MattsNorrbohm** [comment]
Hi @erossignon 

working the issue now. I did make adaptions to the sample_client.js and run that against the sample_server.js with no errors. I will continue my investigations. Might take a while...

**Comment by limengsong** [comment]
@erossignon Hello
I have tried opc ua subscription in two ways, one of which can be successful and the other not. I do n’t know why, please ask, thank you。
```
//This method doesn't work
(async function main() {

    const client = OPCUAClient.create({
        securityMode: MessageSecurityMode.SignAndEncrypt,
        securityPolicy: SecurityPolicy.Basic128Rsa15,
        requestedSessionTimeout: 60000,
        applicationName: "NodeOPCUA-Client",
        endpoint_must_exist: false,
        keepSessionAlive: true,
        certificateFile: "./own/certs/uaclientcpp.der",
        privateKeyFile: "./own/private/uaclientcpp.pem",
        clientName: "lms",
        connectionStrategy: {
            maxRetry: 10,
            initialDelay: 2000,
            maxDelay: 10 * 1000
        }
    });
    await client.connect(endpointUrl);
    //创建会话
    const session = await client.createSession(userIdentityInfo);
    //读取单个NodeId的值信息
    //  const dataValue = await session.read(setReadNode("ns=100;s=015_02.SpindleSpeed.PV", "Value"));
    //  console.log('ns=100;s=015_02.SpindleSpeed.PV =>', dataValue.value.value);

    //建立订阅：
    const subscription = opcua.ClientSubscription.create(session, {
        requestedPublishingInterval: 1000,
        requestedLifetimeCount: 10,
        requestedMaxKeepAliveCount: 10,
        maxNotificationsPerPublish: 10,
        publishingEnabled: true,
        priority: 10
    });
    subscription.on("started", () => {
        console.log("subscription started for 2 seconds - subscriptionId=", subscription.subscriptionId);
    });
    subscription.on("keepalive", () => {
        console.log("keepalive");
    });
    subscription.on("terminated", () => {
        console.log("terminated");
    });

    const monitoredItem = opcua.ClientMonitoredItem.create(subscription, {
            nodeId: opcua.resolveNodeId("ns=100;s=015_02.SpindleSpeed.PV"),
            attributeId: AttributeIds.Value
        }, {
            samplingInterval: 1000,
            discardOldest: true,
            queueSize: 10
        },
        opcua.TimestampsToReturn.Both
    );

    monitoredItem.on("initialized", () => {
        /* do something */
    });
    // monitoredItem.on("changed", (dataValue) => console.log("ns=6;s=DataItem_0000", dataValue.value.value));
    monitoredItem.on("changed", (dataValue) => console.log("订阅实时值", dataValue.toString()));



    //调用OPC UA CallMethod方法
    const getAllDdevByClass = await session.call(setCallMtValue('GetPointsByType("SCALE");'));

    //call调用成功->获取设备实例列表
    if (getAllDdevByClass[0].statusCode._value === 0) {
        let rlt = getAllDdevByClass[0].outputArguments[0].value;
        devList = rlt.split(",");
        if (devList.length > 0) {
            for (let v of devList) {
                let devInstance = {};
                devInstance.pointArr = []; //设备点详情列表
                let desc = await session.read(setReadNode(v, "Description"));
                devInstance.devName = v;
                devInstance.devDesc = desc.value.value.text;
                //获取设备属性列表
                let allPNs = await session.call(setCallMtValue(`GetAllChildObjectName("${v}")`));
                if (allPNs[0].statusCode._value === 0) {
                    let rlt = allPNs[0].outputArguments[0].value;
                    let pnArray = rlt.split(',');
                    //根据点名信息，获取描述信息和数值
                    if (pnArray.length > 0) {
                        for (let pn of pnArray) {
                            let point = {};
                            let pv = await session.read(setReadNode(pn, "Value"));
                            let pd = await session.read(setReadNode(pn, "Description"));
                            if (pd.value.value) {
                                point.pn = v;
                                point.pv = pv.value.value;
                                point.pd = pd.value.value.text;
                            }
                            devInstance.pointArr.push(point);
                        }
                    }
                    //devInstance.devAllPoints = pnArray;
                }
                devListInfo.push(devInstance);
            }
        }
    }
   // console.log('设备实例列表', devListInfo);

    //结束会话
    await client.closeSession(session, true);
    //点开连接
    await client.disconnect();

})();
```
![image](https://user-images.githubusercontent.com/26559533/70582809-b02f0e00-1bf6-11ea-96c8-159f722e0c55.png)

```
// This method can works
async.series([

        // step 1 : connect to
        function (callback) {
            client.connect(endpointUrl, function (err) {
                if (err) {
                    console.log(" cannot connect to endpoint :", endpointUrl);
                } else {
                    console.log("connected !");
                }
                callback(err);
            });
        },

        // step 2 : createSession
        function (callback) {
            const userIdentityInfo = {
                userName: "Admin",
                password: "66666666"
            };
            client.createSession(userIdentityInfo, function (err, session) {
                if (err) {
                    return callback(err);
                }
                the_session = session;
                callback();
            });
        },

        // step 3 : browse
        function (callback) {
            the_session.browse("RootFolder", function (err, browseResult) {
                if (!err) {
                    console.log("Browsing rootfolder: ");
                    for (let reference of browseResult.references) {
                        //console.log( reference.browseName.toString(), reference.nodeId.toString());
                        console.log('reference.browseName', reference.browseName.toString(), 'reference.nodeId', reference.nodeId.toString());
                    }
                }
                callback(err);
            });
        },

        // step 4' : read a variable with read
        function (callback) {
            const maxAge = 0;
            const nodeToRead = {
                nodeId: "ns=100;s=015_02.SpindleSpeed.PV",
                // nodeId: "ns=104;s=SCALE_001",
                attributeId: opcua.AttributeIds.Value
            };

            the_session.read(nodeToRead, maxAge, function (err, dataValue) {
                if (!err) {
                    // console.log(" 当前值 = " , dataValue.value.value);
                    console.log(" 当前值 = ", dataValue.toString());
                }
                callback(err);
            });
        },
        // step 5: install a subscription and monitored item
        //
        // -----------------------------------------
        // create subscription
        function (callback) {
            the_subscription = opcua.ClientSubscription.create(the_session, {
                requestedPublishingInterval: 1000,
                requestedLifetimeCount: 10,
                requestedMaxKeepAliveCount: 10,
                maxNotificationsPerPublish: 10,
                publishingEnabled: true,
                priority: 10
            });

            //console.log('the_subscription', the_subscription);
            the_subscription.on("started", function () {
                console.log("subscription started for 2 seconds - subscriptionId=", the_subscription.subscriptionId);
            }).on("keepalive", function () {
                console.log("keepalive");
            }).on("terminated", function () {
                callback();
            });
            setTimeout(function () {
                the_subscription.terminate();
            }, 10000);


            // install monitored item
            //
            const monitoredItem = opcua.ClientMonitoredItem.create(the_subscription, {
                    nodeId: opcua.resolveNodeId("ns=100;s=015_02.SpindleSpeed.PV"),
                    attributeId: opcua.AttributeIds.Value
                }, {
                    samplingInterval: 1000,
                    discardOldest: true,
                    queueSize: 10
                },
                opcua.TimestampsToReturn.Both
            );

            console.log('monitoredItem', monitoredItem);
            monitoredItem.on("initialized", () => {
                /* do something */
            });
            // monitoredItem.on("changed", (dataValue) => console.log("ns=6;s=DataItem_0000", dataValue.value.value));
            monitoredItem.on("changed", (dataValue) => console.log("订阅实时值", dataValue.toString()));


        },
        // ------------------------- Call method -----------------------------------

        // async function (callback) {

        //         try {
        //             let getAllDevInstances = setCallMtValue('GetPointsByType("SCALE");');
        //             var allDevInsArray = [];
        //             let aa = await methodsToCall(the_session, getAllDevInstances);
        //             console.log('aa', aa);

        //         } catch (err) {
        //             callback(err);
        //         }


        //         // the_session.call(getAllDevInstances, function (err, results) {
        //         //     // results.length.should.eql(1);
        //         //     // results[0].statusCode.should.eql(StatusCodes.Good);
        //         //     let instanceStr = results[0].outputArguments[0].value;
        //         //     let instanceArray = instanceStr.split(',');
        //         //     console.log('设备实例个数为：', instanceArray.length);

        //         //     //console.log('设备实例:',instanceArray);
        //         //     if (instanceArray.length > 0) {
        //         //         let allPointsArray = [];
        //         //         for (let v of instanceArray) {
        //         //             let tmpDev = {};
        //         //             tmpDev.devName = v;
        //         //             let nodeToRead = {
        //         //                 nodeId: v,
        //         //                 attributeId: opcua.AttributeIds.Description
        //         //             };
        //         //             the_session.read(nodeToRead, 0, function (err, dataValue) {
        //         //                 if (!err) {
        //         //                     tmpDev.devDesc = dataValue.value.value.text;
        //         //                 }
        //         //             });

        //         //             let getAllPoints = setCallMtValue(`GetAllChildObjectName("${v}");`);
        //         //             the_session.call(getAllPoints, function (err, results) {
        //         //                 let allPoints = results[0].outputArguments[0].value;
        //         //                 allPointsArray = allPoints.split(',');
        //         //                 tmpDev.pointList = allPointsArray;
        //         //                 console.log('tmpDev', tmpDev);
        //         //                 // for(let i of allPointsArray){
        //         //                 //     let tmpPoint={};
        //         //                 //     tmpPoint.pointName=i;
        //         //                 //     let allPointToRead = {
        //         //                 //         nodeId: i,
        //         //                 //         attributeId: opcua.AttributeIds.Description
        //         //                 //     };
        //         //                 //     the_session.read(allPointToRead, 0, function (err, dataValue) {
        //         //                 //         if (!err) {
        //         //                 //             tmpPoint.pointDesc=dataValue.value.value.text;
        //         //                 //             console.log('tmpPoint',tmpPoint);
        //         //                 //         }
        //         //                 //     });

        //         //                 // }
        //         //             })



        //         //             //console.log('tmpDev',tmpDev);
        //         //         }
        //         //     }
        //         //     //根据设备信息获取全部测点信息并进行读取





        //         //     callback(err);
        //         // });
        //     },

            // ---------------------------- END ---------------------------------------
            // closing session
            //
            function (callback) {
                console.log(" closing session");
                the_session.close(function (err) {

                    console.log(" session closed");
                    callback();
                });
            }


    ],
    function (err) {
        if (err) {
            console.log(" failure ", err);
        } else {
            console.log("done!");
        }
        client.disconnect(function () {});
    });
```
![image](https://user-images.githubusercontent.com/26559533/70582864-e8cee780-1bf6-11ea-917b-85fc54130c6b.png)

**Comment by limengsong** [comment]
@erossignon Hello
There is no obvious difference between the above two writing methods. I refer to this
https://github.com/node-opcua/node-opcua/wiki/2.0.0-breaking-changes

**Comment by erossignon** [comment]
@limengsong  you need to pause before , otherwise the session will be closed before the client has a chance to see a notification from your subscription.
````
// ADD THIS LINE
await new Promise((resolve) => setTimeout(resolve, 10000)); 
await client.closeSession(session, true);
````

Please consider the book  https://leanpub.com/node-opcuabyexample which come with many practical examples...
