### ISSUE TITLE
Error when reading asynchronous Variable of a device

### ISSUE THREAD

**Issue by mtrabelsi** [node-opcua/node-opcua#737]
**Current behavior**

**Describe the bug**

**To Reproduce**
1. create a simple server that contains 1 device and 1 variable and return simple string synchronously 
2. change the same server with returning the same variable in an asynchronous way
3. you will get an error

**Expected behavior**
Should support Asychnrounous fetching

**Gist**
```javascript

/*global require,setInterval,console */
const opcua = require("node-opcua");
// Let's create an instance of OPCUAServer
const server = new opcua.OPCUAServer({
    port: 4334, // the port of the listening socket of the server
    resourcePath: "/test", // this path will be added to the endpoint resource name
     buildInfo : {
        productName: "MySampleServer1",
        buildNumber: "7658",
        buildDate: new Date(2014,5,2)
    }
});

function post_initialize() {
    console.log("initialized");
    function construct_my_address_space(server) {

        const addressSpace = server.engine.addressSpace;
        const namespace = addressSpace.getOwnNamespace();

        // declare a new object
        const device = namespace.addObject({
            organizedBy: addressSpace.rootFolder.objects,
            browseName: "IOTA_GATEWAY_DEVICE"
        });

        namespace.addVariable({
            componentOf: device,
            nodeId: "ns=1;s=iota-mam-writer-reader",
            browseName: "mam reader",
            dataType: "String",
            value: {
                refreshFunc: async function (callback) {
                    setTimeout(()=>{
                        callback(
                            null, 
                            new opcua.Variant({dataType: opcua.DataType.String, value: "reply after 1s" })
                        )
                    }, 1000)
                },
                set: function (variant) {
                    const variable2 = parseFloat(variant.value);
                    return opcua.StatusCodes.Good;
                }
            }
        });
    }
    construct_my_address_space(server);
    server.start(function() {
        console.log("Server is now listening ... ( press CTRL+C to stop)");
        console.log("port ", server.endpoints[0].port);
        const endpointUrl = require("os").hostname();
        console.log(" the primary server endpoint url is ", endpointUrl );


    });
}
server.initialize(post_initialize);

```

Code of the Client

 ```
 
const { OPCUAClient } = require("node-opcua");



(async () => {


    const client = OPCUAClient.create({ endpoint_must_exist: false});
    await client.connect("opc.tcp://localhost:4334");

    const the_session = await client.createSession();
    //browsing the root folder of the OPC Server
    try {
        console.log("Browsing rootfolder...");
        const browseResult = await the_session.browse("RootFolder");
        console.log("Browsing completed!");
        for(let reference of browseResult.references) {
            console.log(reference.displayName.toString(), reference, reference.nodeId.toString());
        }
    } catch (error) {
        console.log("Browsing error", error);
    }

    // step 4 : read a variable with readVariableValue
    try {
        const dataValue = await the_session.readVariableValue("ns=1;s=iota-mam-writer-reader")
        console.log("ns=1;s=iota-mam-writer-reader= " , dataValue.toString());
    } catch (error) {
        console.log("reading error", error);
    }

    await the_session.close();
    await client.disconnect();
})();
```

the server crashes with this error

```
/home/projects/support/github/node_modules/node-opcua-variant/source/variant.ts:413
    options.dataType = options.dataType || DataType.Null;
                    ^
TypeError: Cannot create property 'dataType' on string 'reply after 1s'
    at constructHook (/home/projects/support/github/node_modules/node-opcua-variant/source/variant.ts:413:21)
    at new Variant (/home/projects/support/github/node_modules/node-opcua-variant/source/variant.ts:96:19)
    at new DataValue (/home/projects/support/github/node_modules/node-opcua-data-value/source/datavalue.ts:292:44)
    at coerceDataValue (/home/projects/support/github/node_modules/node-opcua-address-space/src/ua_variable.ts:1733:12)
    at /home/projects/support/github/node_modules/node-opcua-address-space/src/ua_variable.ts:426:46
    at Timeout._onTimeout (/home/projects/support/github/737/server.js:36:25)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

```
 * ( ) my request is related to node-opcua acting as a  OPCUA CLIENT 
  * ( )  my request is related to node-opcua acting as a OPCUA SERVER 

  * ( ) I have installed node-opcua from source ( using git clone)
  * ( ) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: _____
  * OS version: _____
    
    - ( ) Windows : version : _________
    - ( ) Linux   : version : _________
    - ( ) MacOs   : version : catalina 10.15
    - ( ) Raspbian: version : _________
    - ( ) Other   : specify :
   
   * Description of the other OPCUA system I am trying to connect to:
   
     - Name:_________
     - Version:_________
     - Manufacturer/Software vendor:_________
     - link : https://
     

* **node-opcua version:**  : 2.5.0-alpha.10

* **Node:** 
   `node --version` = v12.10.0

**Comment by erossignon** [comment]
RefreshFunc callback expects a DataValue and not a Variant

replace 
```javascript 
namespace.addVariable({
            componentOf: device,
            nodeId: "ns=1;s=iota-mam-writer-reader",
            browseName: "mam reader",
            dataType: "String",
            value: {
                refreshFunc: async function (callback) {
                    setTimeout(()=>{
                        callback(
                            null, 
                            new opcua.Variant({dataType: opcua.DataType.String, value: "reply after 1s" })
                        )
                    }, 1000)
                },
```
with 
```javascript 
namespace.addVariable({
            componentOf: device,
            nodeId: "ns=1;s=iota-mam-writer-reader",
            browseName: "mam reader",
            dataType: "String",
 value: {
                refreshFunc: function (callback) {
                    setTimeout(()=>{
                        callback(
                            null, 
                            new opcua.DataValue({
                                statusCode: opcua.StatusCodes.Good,
                                value:  new opcua.Variant({
                                    dataType: opcua.DataType.String, 
                                    value: "reply after 1s" 
                                })
                            }) 
                        );
                    }, 1000)
                },
```

**Comment by mtrabelsi** [comment]
thanks! worked! 

BTW is there any plan to make this SDK certified with OPC UA Foundation?

thanks

**Comment by erossignon** [comment]
Marwen , the node-opcua sponsoring program will help us to grant the certification process, https://github.com/sponsors/node-opcua , I encourage you to consider it.
