### ISSUE TITLE
"Schema type is already registered" error

### ISSUE THREAD

**Issue by cbaser** [node-opcua/node-opcua#873]
**Current behavior**

I dont know what happened but the server cannot run second time. It gives me the following error.

**Describe the bug**

../OPC-UA/opcua-sample-server/server.js
registerBasicType: {
  name: 'AccessLevelFlag',
  subType: 'Byte',
  defaultValue: [Function: defaultValue],
  coerce: [Function: coerce],
  decode: [Function: decode],
  encode: [Function: encode],
  random: [Function: randomAccessLevel]
}
Error: Basic Type AccessLevelFlag already registered
    at Object.registerBasicType (../OPC-UA/opcua-sample-server/node_modules/node-opcua-factory/dist/factories_basic_type.js:44:15)
    at Object.<anonymous> (../OPC-UA/opcua-sample-server/node_modules/node-opcua-data-model/dist/access_level.js:84:22)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (../OPC-UA/opcua-sample-server/node_modules/node-opcua-data-model/dist/index.js:16:14)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)

Process finished with exit code 1

**To Reproduce**
1. Downloaded the sample server
2. Running it with node server.js

**Expected behavior**
Server runs

**Screenshots**

**Gist**
gist:

 * ( ) my request is related to node-opcua acting as a  OPCUA CLIENT 
  * (x)  my request is related to node-opcua acting as a OPCUA SERVER 

  * ( ) I have installed node-opcua from source ( using git clone)
  * (x) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: _____
  * OS version: _____
    
    - (x) Windows : version : 17134.1667
    - ( ) Linux   : version : _________
    - ( ) MacOs   : version : _________
    - ( ) Raspbian: version : _________
    - ( ) Other   : specify :
   

* **node-opcua version:**  : 2.8.1

* **Node:** 
   `node --version` = v14.2.0

**Comment by cbaser** [comment]
It was a versioning problem, after the update it works. Sorry for the opening the issue
